# generated by datamodel-codegen:
#   filename:  OB11MessageData.schema.json
#   timestamp: 2026-01-20T13:44:08+00:00

from __future__ import annotations
from dataclasses import dataclass
from typing import Any, Literal


@dataclass
class OB11MessageTextData:
    text: str


@dataclass
class OB11MessageText:
    type: Literal["text"]
    data: OB11MessageTextData


@dataclass
class OB11MessageFaceData:
    id: str
    resultId: str | None = None
    chainCount: float | None = None


@dataclass
class OB11MessageFace:
    type: Literal["face"]
    data: OB11MessageFaceData


@dataclass
class OB11MessageMFaceData:
    emoji_package_id: float
    emoji_id: str
    key: str
    summary: str


@dataclass
class OB11MessageMFace:
    type: Literal["mface"]
    data: OB11MessageMFaceData


@dataclass
class OB11MessageAtData:
    qq: str
    name: str | None = None


@dataclass
class OB11MessageAt:
    type: Literal["at"]
    data: OB11MessageAtData


@dataclass
class OB11MessageReplyData:
    id: str


@dataclass
class OB11MessageReply:
    type: Literal["reply"]
    data: OB11MessageReplyData


type PicSubType = Literal[0, 1, 2, 3, 4, 5, 6, 7]
"""
图片子类型枚举
"""


@dataclass
class OB11MessageRecordData:
    file: str
    path: str | None = None
    thumb: str | None = None
    name: str | None = None
    url: str | None = None


@dataclass
class OB11MessageRecord:
    data: OB11MessageRecordData
    type: Literal["record"]


@dataclass
class OB11MessageFileData:
    file: str
    path: str | None = None
    thumb: str | None = None
    name: str | None = None
    url: str | None = None


@dataclass
class OB11MessageFile:
    data: OB11MessageFileData
    type: Literal["file"]


@dataclass
class OB11MessageVideoData:
    file: str
    path: str | None = None
    thumb: str | None = None
    name: str | None = None
    url: str | None = None


@dataclass
class OB11MessageVideo:
    data: OB11MessageVideoData
    type: Literal["video"]


@dataclass
class OB11MessageNodeDataNew:
    text: str


@dataclass
class IdMusicSignPostData:
    type: Literal["qq", "163", "kugou", "migu", "kuwo"]
    id: str | float


@dataclass
class OB11MessageCustomMusicData:
    type: Literal["qq", "163", "kugou", "migu", "kuwo", "custom"]
    url: str
    image: str
    content: str | None = None
    id: Any | None = None
    audio: str | None = None
    title: str | None = None


@dataclass
class OB11MessageCustomMusic:
    type: Literal["music"]
    data: OB11MessageCustomMusicData


@dataclass
class OB11MessageJsonDataConfig:
    token: str


@dataclass
class OB11MessageJsonData:
    data: str | dict[str, Any]
    config: OB11MessageJsonDataConfig | None = None


@dataclass
class OB11MessageJson:
    type: Literal["json"]
    data: OB11MessageJsonData


@dataclass
class OB11MessageDiceData:
    result: float | str


@dataclass
class OB11MessageDice:
    type: Literal["dice"]
    data: OB11MessageDiceData


@dataclass
class OB11MessageRPSData:
    result: float | str


@dataclass
class OB11MessageRPS:
    type: Literal["rps"]
    data: OB11MessageRPSData


@dataclass
class OB11MessageMarkdownData:
    content: str


@dataclass
class OB11MessageMarkdown:
    type: Literal["markdown"]
    data: OB11MessageMarkdownData


@dataclass
class OB11MessageForwardData:
    id: str


@dataclass
class OB11MessageForward:
    type: Literal["forward"]
    data: OB11MessageForwardData


@dataclass
class OB11MessageContextData:
    type: Literal["qq", "group"]
    id: str


@dataclass
class OB11MessageContext:
    type: Literal["contact"]
    data: OB11MessageContextData


@dataclass
class OB11MessagePokeData:
    type: str
    id: str


@dataclass
class OB11MessagePoke:
    type: Literal["poke"]
    data: OB11MessagePokeData


@dataclass
class OB11MessageImageData:
    file: str
    summary: str | None = None
    sub_type: PicSubType | None = None
    path: str | None = None
    thumb: str | None = None
    name: str | None = None
    url: str | None = None


@dataclass
class OB11MessageImage:
    data: OB11MessageImageData
    type: Literal["image"]


@dataclass
class OB11MessageIdMusic:
    type: Literal["music"]
    data: IdMusicSignPostData


type Model = OB11MessageData


type OB11MessageData = (
    OB11MessageText
    | OB11MessageFace
    | OB11MessageMFace
    | OB11MessageAt
    | OB11MessageReply
    | OB11MessageImage
    | OB11MessageRecord
    | OB11MessageFile
    | OB11MessageVideo
    | OB11MessageNode
    | OB11MessageIdMusic
    | OB11MessageCustomMusic
    | OB11MessageJson
    | OB11MessageDice
    | OB11MessageRPS
    | OB11MessageMarkdown
    | OB11MessageForward
    | OB11MessageContext
    | OB11MessagePoke
)


@dataclass
class OB11MessageNodeData:
    nickname: str
    content: OB11MessageMixType
    id: str | None = None
    user_id: float | str | None = None
    uin: float | str | None = None
    name: str | None = None
    source: str | None = None
    news: list[OB11MessageNodeDataNew] | None = None
    summary: str | None = None
    prompt: str | None = None
    time: str | None = None


@dataclass
class OB11MessageNode:
    type: Literal["node"]
    data: OB11MessageNodeData


type OB11MessageMixType = list[OB11MessageData] | str | OB11MessageData
