# generated by datamodel-codegen:
#   filename:  MessageData.schema.json
#   timestamp: 2026-01-22T10:34:25+00:00

from __future__ import annotations
from .base import MessageSegment
from dataclasses import dataclass
from typing import Any, Literal, ClassVar

