# generated by datamodel-codegen:
#   filename:  OB11MessageData.schema.json
#   timestamp: 2026-01-20T13:44:08+00:00

from __future__ import annotations
from .base import SegmentDataTypeBase, SegmentDataBase, MessageSegment
from dataclasses import dataclass
from typing import Any, Literal, NotRequired


class OB11MessageTextDataType(SegmentDataTypeBase):
    text: str


class OB11MessageFaceDataType(SegmentDataTypeBase):
    id: str
    resultId: NotRequired[str]
    chainCount: NotRequired[int]


class OB11MessageMFaceDataType(SegmentDataTypeBase):
    emoji_package_id: int
    emoji_id: str
    key: str
    summary: str


class OB11MessageAtDataType(SegmentDataTypeBase):
    qq: str
    name: NotRequired[str]


class OB11MessageReplyDataType(SegmentDataTypeBase):
    id: str
"""
图片子类型枚举
"""


class OB11MessageRecordDataType(SegmentDataTypeBase):
    path: NotRequired[str]
    thumb: NotRequired[str]
    name: NotRequired[str]
    file: str
    url: NotRequired[str]


class OB11MessageFileDataType(SegmentDataTypeBase):
    path: NotRequired[str]
    thumb: NotRequired[str]
    name: NotRequired[str]
    file: str
    url: NotRequired[str]


class OB11MessageVideoDataType(SegmentDataTypeBase):
    path: NotRequired[str]
    thumb: NotRequired[str]
    name: NotRequired[str]
    file: str
    url: NotRequired[str]


class IdMusicSignPostDataType(SegmentDataTypeBase):
    type: Literal["qq", "163", "kugou", "migu", "kuwo"]
    id: str | int


class OB11MessageCustomMusicDataType(SegmentDataTypeBase):
    content: NotRequired[str]
    type: Literal["qq", "163", "kugou", "migu", "kuwo", "custom"]
    id: NotRequired[Any]
    url: str
    audio: NotRequired[str]
    title: NotRequired[str]
    image: str


class OB11MessageJsonDataType(SegmentDataTypeBase):
    config: NotRequired[OB11MessageJsonDataConfig]
    data: str | dict[str, Any]


class OB11MessageDiceDataType(SegmentDataTypeBase):
    result: int | str


class OB11MessageRPSDataType(SegmentDataTypeBase):
    result: int | str


class OB11MessageMarkdownDataType(SegmentDataTypeBase):
    content: str


class OB11MessageForwardDataType(SegmentDataTypeBase):
    id: str


class OB11MessageContextDataType(SegmentDataTypeBase):
    type: Literal["qq", "group"]
    id: str


class OB11MessagePokeDataType(SegmentDataTypeBase):
    type: str
    id: str


class OB11MessageImageDataType(SegmentDataTypeBase):
    summary: NotRequired[str]
    sub_type: NotRequired[PicSubType]
    path: NotRequired[str]
    thumb: NotRequired[str]
    name: NotRequired[str]
    file: str
    url: NotRequired[str]


class OB11MessageNodeDataType(SegmentDataTypeBase):
    id: NotRequired[str]
    user_id: NotRequired[int | str]
    uin: NotRequired[int | str]
    nickname: str
    name: NotRequired[str]
    content: OB11MessageMixType
    source: NotRequired[str]
    news: NotRequired[list[OB11MessageNodeDataNew]]
    summary: NotRequired[str]
    prompt: NotRequired[str]
    time: NotRequired[str]


# generated by datamodel-codegen:
#   filename:  OB11MessageData.schema.json
#   timestamp: 2026-01-20T13:44:08+00:00




@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageTextData(SegmentDataBase):
    text: str


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageText(MessageSegment):
    type: Literal["text"]
    data: OB11MessageTextData


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageFaceData(SegmentDataBase):
    id: str
    resultId: str | None = None
    chainCount: int | None = None


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageFace(MessageSegment):
    type: Literal["face"]
    data: OB11MessageFaceData


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageMFaceData(SegmentDataBase):
    emoji_package_id: int
    emoji_id: str
    key: str
    summary: str


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageMFace(MessageSegment):
    type: Literal["mface"]
    data: OB11MessageMFaceData


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageAtData(SegmentDataBase):
    qq: str
    name: str | None = None


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageAt(MessageSegment):
    type: Literal["at"]
    data: OB11MessageAtData


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageReplyData(SegmentDataBase):
    id: str


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageReply(MessageSegment):
    type: Literal["reply"]
    data: OB11MessageReplyData


type PicSubType = Literal[0, 1, 2, 3, 4, 5, 6, 7]
"""
图片子类型枚举
"""


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageRecordData(SegmentDataBase):
    file: str
    path: str | None = None
    thumb: str | None = None
    name: str | None = None
    url: str | None = None


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageRecord(MessageSegment):
    data: OB11MessageRecordData
    type: Literal["record"]


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageFileData(SegmentDataBase):
    file: str
    path: str | None = None
    thumb: str | None = None
    name: str | None = None
    url: str | None = None


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageFile(MessageSegment):
    data: OB11MessageFileData
    type: Literal["file"]


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageVideoData(SegmentDataBase):
    file: str
    path: str | None = None
    thumb: str | None = None
    name: str | None = None
    url: str | None = None


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageVideo(MessageSegment):
    data: OB11MessageVideoData
    type: Literal["video"]


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageNodeDataNew:
    text: str


@dataclass(slots=True, frozen=True, kw_only=True)
class IdMusicSignPostData(SegmentDataBase):
    type: Literal["qq", "163", "kugou", "migu", "kuwo"]
    id: str | int


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageCustomMusicData(SegmentDataBase):
    type: Literal["qq", "163", "kugou", "migu", "kuwo", "custom"]
    url: str
    image: str
    content: str | None = None
    id: Any | None = None
    audio: str | None = None
    title: str | None = None


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageCustomMusic(MessageSegment):
    type: Literal["music"]
    data: OB11MessageCustomMusicData


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageJsonDataConfig:
    token: str


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageJsonData(SegmentDataBase):
    data: str | dict[str, Any]
    config: OB11MessageJsonDataConfig | None = None


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageJson(MessageSegment):
    type: Literal["json"]
    data: OB11MessageJsonData


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageDiceData(SegmentDataBase):
    result: int | str


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageDice(MessageSegment):
    type: Literal["dice"]
    data: OB11MessageDiceData


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageRPSData(SegmentDataBase):
    result: int | str


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageRPS(MessageSegment):
    type: Literal["rps"]
    data: OB11MessageRPSData


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageMarkdownData(SegmentDataBase):
    content: str


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageMarkdown(MessageSegment):
    type: Literal["markdown"]
    data: OB11MessageMarkdownData


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageForwardData(SegmentDataBase):
    id: str


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageForward(MessageSegment):
    type: Literal["forward"]
    data: OB11MessageForwardData


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageContextData(SegmentDataBase):
    type: Literal["qq", "group"]
    id: str


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageContext(MessageSegment):
    type: Literal["contact"]
    data: OB11MessageContextData


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessagePokeData(SegmentDataBase):
    type: str
    id: str


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessagePoke(MessageSegment):
    type: Literal["poke"]
    data: OB11MessagePokeData


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageImageData(SegmentDataBase):
    file: str
    summary: str | None = None
    sub_type: PicSubType | None = None
    path: str | None = None
    thumb: str | None = None
    name: str | None = None
    url: str | None = None


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageImage(MessageSegment):
    data: OB11MessageImageData
    type: Literal["image"]


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageIdMusic(MessageSegment):
    type: Literal["music"]
    data: IdMusicSignPostData


type Model = OB11MessageData


type OB11MessageData = (
    OB11MessageText
    | OB11MessageFace
    | OB11MessageMFace
    | OB11MessageAt
    | OB11MessageReply
    | OB11MessageImage
    | OB11MessageRecord
    | OB11MessageFile
    | OB11MessageVideo
    | OB11MessageNode
    | OB11MessageIdMusic
    | OB11MessageCustomMusic
    | OB11MessageJson
    | OB11MessageDice
    | OB11MessageRPS
    | OB11MessageMarkdown
    | OB11MessageForward
    | OB11MessageContext
    | OB11MessagePoke
)


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageNodeData(SegmentDataBase):
    nickname: str
    content: OB11MessageMixType
    id: str | None = None
    user_id: int | str | None = None
    uin: int | str | None = None
    name: str | None = None
    source: str | None = None
    news: list[OB11MessageNodeDataNew] | None = None
    summary: str | None = None
    prompt: str | None = None
    time: str | None = None


@dataclass(slots=True, frozen=True, kw_only=True)
class OB11MessageNode(MessageSegment):
    type: Literal["node"]
    data: OB11MessageNodeData


type OB11MessageMixType = list[OB11MessageData] | str | OB11MessageData
