# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-07T01:30:14+00:00

from __future__ import annotations
from typing import Any, Literal
from dataclasses import dataclass


@dataclass
class BaseResponse:
    status: str
    """
    状态 (ok/failed)
    """
    retcode: float
    """
    返回码
    """
    message: str | None = None
    """
    消息
    """
    wording: str | None = None
    """
    提示
    """
    stream: Literal["stream-action", "normal-action"] | None = None
    """
    流式响应
    """


type EmptyData = None
"""
无数据
"""


@dataclass
class FileBaseData:
    """
    文件消息段基础数据
    """

    file: str
    """
    文件路径/URL/file:///
    """
    path: str | None = None
    """
    文件路径
    """
    url: str | None = None
    """
    文件URL
    """
    name: str | None = None
    """
    文件名
    """
    thumb: str | None = None
    """
    缩略图
    """


@dataclass
class OB11MessageAtData:
    qq: str
    """
    QQ号或all
    """
    name: str | None = None
    """
    显示名称
    """


@dataclass
class OB11MessageAt:
    """
    @消息段
    """

    type: Literal["at"]
    data: OB11MessageAtData


@dataclass
class OB11MessageContactData:
    type: Literal["qq", "group"]
    """
    联系人类型
    """
    id: str
    """
    联系人ID
    """


@dataclass
class OB11MessageContact:
    """
    联系人消息段
    """

    type: Literal["contact"]
    data: OB11MessageContactData


@dataclass
class OB11MessageCustomMusicData:
    type: Literal["qq", "163", "kugou", "migu", "kuwo", "custom"]
    """
    音乐平台类型
    """
    id: None
    url: str
    """
    点击后跳转URL
    """
    image: str
    """
    封面图片URL
    """
    audio: str | None = None
    """
    音频URL
    """
    title: str | None = None
    """
    音乐标题
    """
    content: str | None = None
    """
    音乐简介
    """


@dataclass
class OB11MessageCustomMusic:
    """
    自定义音乐消息段
    """

    type: Literal["music"]
    data: OB11MessageCustomMusicData


@dataclass
class OB11MessageDiceData:
    result: float | str
    """
    骰子结果
    """


@dataclass
class OB11MessageDice:
    """
    骰子消息段
    """

    type: Literal["dice"]
    data: OB11MessageDiceData


@dataclass
class OB11MessageFaceData:
    id: str
    """
    表情ID
    """
    resultId: str | None = None
    """
    结果ID
    """
    chainCount: float | None = None
    """
    连击数
    """


@dataclass
class OB11MessageFace:
    """
    QQ表情消息段
    """

    type: Literal["face"]
    data: OB11MessageFaceData


@dataclass
class OB11MessageFileBase:
    """
    文件消息基础接口
    """

    data: FileBaseData


@dataclass
class OB11MessageFile:
    """
    文件消息段
    """

    type: Literal["file"]
    data: FileBaseData


@dataclass
class OB11MessageFlashTransferData:
    fileSetId: str
    """
    文件集ID
    """


@dataclass
class OB11MessageFlashTransfer:
    """
    QQ闪传消息段
    """

    type: Literal["flashtransfer"]
    data: OB11MessageFlashTransferData


@dataclass
class OB11MessageForwardData:
    id: str
    """
    合并转发ID
    """
    content: dict[str, Any] | None = None
    """
    消息内容 (OB11Message[])
    """


@dataclass
class OB11MessageForward:
    """
    合并转发消息段
    """

    type: Literal["forward"]
    data: OB11MessageForwardData


@dataclass
class OB11MessageIdMusicData:
    type: Literal["qq", "163", "kugou", "migu", "kuwo"]
    """
    音乐平台类型
    """
    id: str | float
    """
    音乐ID
    """


@dataclass
class OB11MessageIdMusic:
    """
    ID音乐消息段
    """

    type: Literal["music"]
    data: OB11MessageIdMusicData


@dataclass
class Data(FileBaseData):
    summary: str | None = None
    """
    图片摘要
    """
    sub_type: float | None = None
    """
    图片子类型
    """


@dataclass
class OB11MessageImage:
    """
    图片消息段
    """

    type: Literal["image"]
    data: Data


@dataclass
class OB11MessageJsonDataConfig:
    token: str
    """
    token
    """


@dataclass
class OB11MessageJsonData:
    data: str | dict[str, Any]
    """
    JSON数据
    """
    config: OB11MessageJsonDataConfig | None = None


@dataclass
class OB11MessageJson:
    """
    JSON消息段
    """

    type: Literal["json"]
    data: OB11MessageJsonData


@dataclass
class OB11MessageLocationData:
    lat: str | float
    """
    纬度
    """
    lon: str | float
    """
    经度
    """
    title: str | None = None
    """
    标题
    """
    content: str | None = None
    """
    内容
    """


@dataclass
class OB11MessageLocation:
    """
    位置消息段
    """

    type: Literal["location"]
    data: OB11MessageLocationData


@dataclass
class OB11MessageMFaceData:
    emoji_package_id: float
    """
    表情包ID
    """
    emoji_id: str
    """
    表情ID
    """
    key: str
    """
    表情key
    """
    summary: str
    """
    表情摘要
    """


@dataclass
class OB11MessageMFace:
    """
    商城表情消息段
    """

    type: Literal["mface"]
    data: OB11MessageMFaceData


@dataclass
class OB11MessageMarkdownData:
    content: str
    """
    Markdown内容
    """


@dataclass
class OB11MessageMarkdown:
    """
    Markdown消息段
    """

    type: Literal["markdown"]
    data: OB11MessageMarkdownData


@dataclass
class OB11MessageMiniAppData:
    data: str
    """
    小程序数据
    """


@dataclass
class OB11MessageMiniApp:
    """
    小程序消息段
    """

    type: Literal["miniapp"]
    data: OB11MessageMiniAppData


@dataclass
class OB11MessageNodeDataNew:
    text: str
    """
    新闻文本
    """


@dataclass
class OB11MessageNodeData:
    nickname: str
    """
    发送者昵称
    """
    content: dict[str, Any]
    """
    消息内容 (OB11MessageMixType)
    """
    id: str | None = None
    """
    转发消息ID
    """
    user_id: float | str | None = None
    """
    发送者QQ号
    """
    uin: float | str | None = None
    """
    发送者QQ号(兼容go-cqhttp)
    """
    name: str | None = None
    """
    发送者昵称(兼容go-cqhttp)
    """
    source: str | None = None
    """
    消息来源
    """
    news: list[OB11MessageNodeDataNew] | None = None
    summary: str | None = None
    """
    摘要
    """
    prompt: str | None = None
    """
    提示
    """
    time: str | None = None
    """
    时间
    """


@dataclass
class OB11MessageNode:
    """
    合并转发消息节点
    """

    type: Literal["node"]
    data: OB11MessageNodeData


@dataclass
class OB11MessageOnlineFileData:
    msgId: str
    """
    消息ID
    """
    elementId: str
    """
    元素ID
    """
    fileName: str
    """
    文件名
    """
    fileSize: str
    """
    文件大小
    """
    isDir: bool
    """
    是否为目录
    """


@dataclass
class OB11MessageOnlineFile:
    """
    在线文件消息段
    """

    type: Literal["onlinefile"]
    data: OB11MessageOnlineFileData


@dataclass
class OB11MessagePokeData:
    type: str
    """
    戳一戳类型
    """
    id: str
    """
    戳一戳ID
    """


@dataclass
class OB11MessagePoke:
    """
    戳一戳消息段
    """

    type: Literal["poke"]
    data: OB11MessagePokeData


@dataclass
class OB11MessageRPSData:
    result: float | str
    """
    猜拳结果
    """


@dataclass
class OB11MessageRPS:
    """
    猜拳消息段
    """

    type: Literal["rps"]
    data: OB11MessageRPSData


@dataclass
class OB11MessageRecord:
    """
    语音消息段
    """

    type: Literal["record"]
    data: FileBaseData


@dataclass
class OB11MessageReplyData:
    id: str | None = None
    """
    消息ID的短ID映射
    """
    seq: float | None = None
    """
    消息序列号，优先使用
    """


@dataclass
class OB11MessageReply:
    """
    回复消息段
    """

    type: Literal["reply"]
    data: OB11MessageReplyData


@dataclass
class OB11MessageEmojiLikesListItem:
    emoji_id: str
    """
    表情ID
    """
    emoji_type: str
    """
    表情类型
    """
    likes_cnt: str
    """
    点赞数
    """


@dataclass
class OB11MessageTextData:
    text: str
    """
    纯文本内容
    """


@dataclass
class OB11MessageText:
    """
    纯文本消息段
    """

    type: Literal["text"]
    data: OB11MessageTextData


@dataclass
class OB11MessageVideo:
    """
    视频消息段
    """

    type: Literal["video"]
    data: FileBaseData


@dataclass
class OB11MessageXmlData:
    data: str
    """
    XML数据
    """


@dataclass
class OB11MessageXml:
    """
    XML消息段
    """

    type: Literal["xml"]
    data: OB11MessageXmlData


@dataclass
class OB11PostSendMsgNew:
    text: str
    """
    文本
    """


@dataclass
class OB11Sender:
    """
    OneBot 11 发送者信息
    """

    user_id: float | str
    """
    发送者QQ号
    """
    nickname: str
    """
    发送者昵称
    """
    card: str | None = None
    """
    群名片
    """
    role: str | None = None
    """
    角色
    """
    sex: str | None = None
    """
    性别
    """
    age: float | None = None
    """
    年龄
    """
    area: str | None = None
    """
    地区
    """
    level: str | None = None
    """
    等级
    """
    title: str | None = None
    """
    头衔
    """


@dataclass
class OB11GroupMember:
    """
    OneBot 11 群成员信息
    """

    group_id: float
    """
    群号
    """
    user_id: float
    """
    QQ号
    """
    nickname: str
    """
    昵称
    """
    card: str | None = None
    """
    名片
    """
    sex: str | None = None
    """
    性别
    """
    age: float | None = None
    """
    年龄
    """
    join_time: float | None = None
    """
    入群时间戳
    """
    last_sent_time: float | None = None
    """
    最后发言时间戳
    """
    level: str | None = None
    """
    等级
    """
    qq_level: float | None = None
    """
    QQ等级
    """
    role: str | None = None
    """
    角色 (owner/admin/member)
    """
    title: str | None = None
    """
    头衔
    """
    area: str | None = None
    """
    地区
    """
    unfriendly: bool | None = None
    """
    是否不良记录
    """
    title_expire_time: float | None = None
    """
    头衔过期时间
    """
    card_changeable: bool | None = None
    """
    是否允许修改名片
    """
    shut_up_timestamp: float | None = None
    """
    禁言截止时间戳
    """
    is_robot: bool | None = None
    """
    是否为机器人
    """
    qage: float | None = None
    """
    Q龄
    """


@dataclass
class OB11Group:
    """
    OneBot 11 群信息
    """

    group_all_shut: float
    """
    是否全员禁言
    """
    group_remark: str
    """
    群备注
    """
    group_id: float
    """
    群号
    """
    group_name: str
    """
    群名称
    """
    member_count: float | None = None
    """
    成员人数
    """
    max_member_count: float | None = None
    """
    最大成员人数
    """


@dataclass
class EmojiLikesListItem:
    emoji_id: str
    """
    表情符号ID
    """
    emoji_type: str
    """
    表情符号类型
    """
    likes_cnt: str
    """
    点赞数
    """


@dataclass
class OB11Notify:
    """
    OneBot 11 通知信息
    """

    request_id: float
    """
    请求ID
    """
    invitor_uin: float
    """
    邀请者QQ
    """
    invitor_nick: str
    """
    邀请者昵称
    """
    group_id: float
    """
    群号
    """
    group_name: str
    """
    群名称
    """
    message: str
    """
    附言
    """
    checked: bool
    """
    是否已处理
    """
    actor: float
    """
    操作者QQ
    """
    requester_nick: str
    """
    申请者昵称
    """


@dataclass
class OB11User:
    """
    OneBot 11 用户信息
    """

    user_id: float
    """
    QQ号
    """
    nickname: str
    """
    昵称
    """
    birthday_year: float | None = None
    """
    出生年份
    """
    birthday_month: float | None = None
    """
    出生月份
    """
    birthday_day: float | None = None
    """
    出生日期
    """
    phone_num: str | None = None
    """
    手机号
    """
    email: str | None = None
    """
    邮箱
    """
    category_id: float | None = None
    """
    分组ID
    """
    remark: str | None = None
    """
    备注
    """
    sex: str | None = None
    """
    性别
    """
    level: float | None = None
    """
    等级
    """
    age: float | None = None
    """
    年龄
    """
    qid: str | None = None
    """
    QID
    """
    login_days: float | None = None
    """
    登录天数
    """
    categoryName: str | None = None
    """
    分组名称
    """
    categoryId: float | None = None
    """
    分组ID
    """


@dataclass
class OB11LatestMessageSender:
    user_id: float
    """
    用户QQ号
    """
    nickname: str
    """
    用户昵称
    """
    card: str | None = None
    """
    用户名片
    """
    role: str | None = None
    """
    用户角色
    """


@dataclass
class OB11LatestMessage:
    """
    最后一条消息
    """

    self_id: float
    """
    发送者QQ号
    """
    user_id: float
    """
    接收者QQ号
    """
    time: float
    """
    时间戳
    """
    real_seq: str
    """
    消息序号
    """
    message_type: str
    """
    消息类型
    """
    sender: OB11LatestMessageSender
    raw_message: str
    """
    原始消息
    """
    font: float
    """
    字体大小
    """
    sub_type: str
    """
    子类型
    """
    message: dict[str, Any]
    """
    消息内容
    """
    message_format: str
    """
    消息格式
    """
    post_type: str
    """
    发布类型
    """
    group_id: float
    """
    群号
    """
    group_name: str
    """
    群名称
    """


type OB11MessageData = (
    OB11MessageText
    | OB11MessageFace
    | OB11MessageMFace
    | OB11MessageAt
    | OB11MessageReply
    | OB11MessageImage
    | OB11MessageRecord
    | OB11MessageVideo
    | OB11MessageFile
    | OB11MessageIdMusic
    | OB11MessageCustomMusic
    | OB11MessagePoke
    | OB11MessageDice
    | OB11MessageRPS
    | OB11MessageContact
    | OB11MessageLocation
    | OB11MessageJson
    | OB11MessageXml
    | OB11MessageMarkdown
    | OB11MessageMiniApp
    | OB11MessageNode
    | OB11MessageForward
    | OB11MessageOnlineFile
    | OB11MessageFlashTransfer
)
"""
OneBot 11 消息段
"""


type OB11MessageMixType = list[OB11MessageData] | str | OB11MessageData
"""
OneBot 11 消息混合类型
"""


@dataclass
class OB11Message:
    """
    OneBot 11 完整消息对象
    """

    time: float
    """
    消息时间戳
    """
    message_id: float
    """
    消息ID
    """
    message_seq: float
    """
    消息序列号
    """
    real_id: float
    """
    真实ID
    """
    user_id: float | str
    """
    发送者QQ号
    """
    message_type: Literal["private", "group"]
    """
    消息类型
    """
    sender: OB11Sender
    message: list[OB11MessageData] | str
    """
    消息内容
    """
    message_format: Literal["array", "string"]
    """
    消息格式
    """
    raw_message: str
    """
    原始消息
    """
    font: float
    """
    字体
    """
    real_seq: str | None = None
    """
    真实序列号
    """
    temp_source: float | None = None
    """
    临时会话来源
    """
    message_sent_type: str | None = None
    """
    消息发送类型
    """
    target_id: float | None = None
    """
    目标ID
    """
    self_id: float | None = None
    """
    机器人QQ号
    """
    group_id: float | str | None = None
    """
    群号
    """
    group_name: str | None = None
    """
    群名称
    """
    sub_type: Literal["friend", "group", "normal"] | None = None
    """
    消息子类型
    """
    post_type: str | None = None
    """
    上报类型
    """
    raw: dict[str, Any] | None = None
    """
    原始消息对象
    """
    emoji_likes_list: list[OB11MessageEmojiLikesListItem] | None = None
    """
    表情点赞列表
    """


@dataclass
class OB11PostSendMsg:
    """
    OneBot 11 发送消息请求
    """

    message: OB11MessageMixType
    message_type: Literal["private", "group"] | None = None
    """
    消息类型
    """
    user_id: str | None = None
    """
    用户QQ号
    """
    group_id: str | None = None
    """
    群号
    """
    messages: OB11MessageMixType | None = None
    auto_escape: bool | str | None = None
    """
    是否作为纯文本发送
    """
    source: str | None = None
    """
    消息来源
    """
    news: list[OB11PostSendMsgNew] | None = None
    summary: str | None = None
    """
    摘要
    """
    prompt: str | None = None
    """
    提示
    """
    time: str | None = None
    """
    时间
    """


@dataclass
class OB11ActionMessage(OB11LatestMessage):
    """
    OneBot 11 消息信息
    """

    message_id: float
    """
    消息ID
    """
    message_seq: float
    """
    消息序列号
    """
    emoji_likes_list: list[EmojiLikesListItem]
