# generated by datamodel-codegen:
#   filename:  OB11MessageData.schema.json
#   timestamp: 2026-01-20T10:59:24+00:00

from __future__ import annotations
from typing_extensions import TypedDict
from typing import Any, Literal, NotRequired


class OB11MessageTextData(TypedDict, closed=True):
    text: str


class OB11MessageText(TypedDict, closed=True):
    type: Literal["text"]
    data: OB11MessageTextData


class OB11MessageFaceData(TypedDict, closed=True):
    id: str
    resultId: NotRequired[str]
    chainCount: NotRequired[float]


class OB11MessageFace(TypedDict, closed=True):
    type: Literal["face"]
    data: OB11MessageFaceData


class OB11MessageMFaceData(TypedDict, closed=True):
    emoji_package_id: float
    emoji_id: str
    key: str
    summary: str


class OB11MessageMFace(TypedDict, closed=True):
    type: Literal["mface"]
    data: OB11MessageMFaceData


class OB11MessageAtData(TypedDict, closed=True):
    qq: str
    name: NotRequired[str]


class OB11MessageAt(TypedDict, closed=True):
    type: Literal["at"]
    data: OB11MessageAtData


class OB11MessageReplyData(TypedDict, closed=True):
    id: str


class OB11MessageReply(TypedDict, closed=True):
    type: Literal["reply"]
    data: OB11MessageReplyData


type PicSubType = Literal[0, 1, 2, 3, 4, 5, 6, 7]
"""
图片子类型枚举
"""


class OB11MessageRecordData(TypedDict, closed=True):
    path: NotRequired[str]
    thumb: NotRequired[str]
    name: NotRequired[str]
    file: str
    url: NotRequired[str]


class OB11MessageRecord(TypedDict, closed=True):
    data: OB11MessageRecordData
    type: Literal["record"]


class OB11MessageFileData(TypedDict, closed=True):
    path: NotRequired[str]
    thumb: NotRequired[str]
    name: NotRequired[str]
    file: str
    url: NotRequired[str]


class OB11MessageFile(TypedDict, closed=True):
    data: OB11MessageFileData
    type: Literal["file"]


class OB11MessageVideoData(TypedDict, closed=True):
    path: NotRequired[str]
    thumb: NotRequired[str]
    name: NotRequired[str]
    file: str
    url: NotRequired[str]


class OB11MessageVideo(TypedDict, closed=True):
    data: OB11MessageVideoData
    type: Literal["video"]


class OB11MessageNodeDataNew(TypedDict, closed=True):
    text: str


class IdMusicSignPostData(TypedDict, closed=True):
    type: Literal["qq", "163", "kugou", "migu", "kuwo"]
    id: str | float


class OB11MessageCustomMusicData(TypedDict, closed=True):
    content: NotRequired[str]
    type: Literal["qq", "163", "kugou", "migu", "kuwo", "custom"]
    id: NotRequired[Any]
    url: str
    audio: NotRequired[str]
    title: NotRequired[str]
    image: str


class OB11MessageCustomMusic(TypedDict, closed=True):
    type: Literal["music"]
    data: OB11MessageCustomMusicData


class OB11MessageJsonDataConfig(TypedDict, closed=True):
    token: str


class OB11MessageJsonData(TypedDict, closed=True):
    config: NotRequired[OB11MessageJsonDataConfig]
    data: str | dict[str, Any]


class OB11MessageJson(TypedDict, closed=True):
    type: Literal["json"]
    data: OB11MessageJsonData


class OB11MessageDiceData(TypedDict, closed=True):
    result: float | str


class OB11MessageDice(TypedDict, closed=True):
    type: Literal["dice"]
    data: OB11MessageDiceData


class OB11MessageRPSData(TypedDict, closed=True):
    result: float | str


class OB11MessageRPS(TypedDict, closed=True):
    type: Literal["rps"]
    data: OB11MessageRPSData


class OB11MessageMarkdownData(TypedDict, closed=True):
    content: str


class OB11MessageMarkdown(TypedDict, closed=True):
    type: Literal["markdown"]
    data: OB11MessageMarkdownData


class OB11MessageForwardData(TypedDict, closed=True):
    id: str


class OB11MessageForward(TypedDict, closed=True):
    type: Literal["forward"]
    data: OB11MessageForwardData


class OB11MessageContextData(TypedDict, closed=True):
    type: Literal["qq", "group"]
    id: str


class OB11MessageContext(TypedDict, closed=True):
    type: Literal["contact"]
    data: OB11MessageContextData


class OB11MessagePokeData(TypedDict, closed=True):
    type: str
    id: str


class OB11MessagePoke(TypedDict, closed=True):
    type: Literal["poke"]
    data: OB11MessagePokeData


class OB11MessageImageData(TypedDict, closed=True):
    summary: NotRequired[str]
    sub_type: NotRequired[PicSubType]
    path: NotRequired[str]
    thumb: NotRequired[str]
    name: NotRequired[str]
    file: str
    url: NotRequired[str]


class OB11MessageImage(TypedDict, closed=True):
    data: OB11MessageImageData
    type: Literal["image"]


class OB11MessageIdMusic(TypedDict, closed=True):
    type: Literal["music"]
    data: IdMusicSignPostData


type Model = OB11MessageData


type OB11MessageData = (
    OB11MessageText
    | OB11MessageFace
    | OB11MessageMFace
    | OB11MessageAt
    | OB11MessageReply
    | OB11MessageImage
    | OB11MessageRecord
    | OB11MessageFile
    | OB11MessageVideo
    | OB11MessageNode
    | OB11MessageIdMusic
    | OB11MessageCustomMusic
    | OB11MessageJson
    | OB11MessageDice
    | OB11MessageRPS
    | OB11MessageMarkdown
    | OB11MessageForward
    | OB11MessageContext
    | OB11MessagePoke
)


class OB11MessageNodeData(TypedDict, closed=True):
    id: NotRequired[str]
    user_id: NotRequired[float | str]
    uin: NotRequired[float | str]
    nickname: str
    name: NotRequired[str]
    content: OB11MessageMixType
    source: NotRequired[str]
    news: NotRequired[list[OB11MessageNodeDataNew]]
    summary: NotRequired[str]
    prompt: NotRequired[str]
    time: NotRequired[str]


class OB11MessageNode(TypedDict, closed=True):
    type: Literal["node"]
    data: OB11MessageNodeData


type OB11MessageMixType = list[OB11MessageData] | str | OB11MessageData
