# src/napcat/__init__.py

__version__ = "0.3.4"

from . import types
from .client import NapCatClient
from .server import ReverseWebSocketServer

# 统一透传 types 的全量导出（自动更新）
from .types import (
    RPS,
    At,
    BotOfflineEvent,
    Contact,
    CustomMusic,
    Dice,
    Face,
    File,
    FlashTransfer,
    Forward,
    FriendAddNoticeEvent,
    FriendPokeEvent,
    FriendRecallNoticeEvent,
    FriendRequestEvent,
    GroupAdminNoticeEvent,
    GroupBanEvent,
    GroupCardEvent,
    GroupDecreaseEvent,
    GroupEssenceEvent,
    GroupGrayTipEvent,
    GroupIncreaseEvent,
    GroupMessageEvent,
    GroupMsgEmojiLikeEvent,
    GroupNameEvent,
    GroupNoticeEvent,
    GroupPokeEvent,
    GroupRecallNoticeEvent,
    GroupRequestEvent,
    GroupTitleEvent,
    GroupUploadFile,
    GroupUploadNoticeEvent,
    HeartbeatEvent,
    HeartbeatStatus,
    IdMusic,
    Image,
    InputStatusEvent,
    Json,
    LifecycleMetaEvent,
    Location,
    Markdown,
    Message,
    MessageEvent,
    MessageSegment,
    MessageSender,
    MetaEvent,
    MFace,
    MiniApp,
    MsgEmojiLike,
    # >>> AUTO-GENERATED: TYPES IMPORTS START
    NapCatEvent,
    Node,
    NoticeEvent,
    OnlineFile,
    OnlineFileNoticeEvent,
    OnlineFileReceiveEvent,
    OnlineFileSendEvent,
    Poke,
    PokeEvent,
    PrivateMessageEvent,
    ProfileLikeEvent,
    Record,
    Reply,
    RequestEvent,
    Text,
    UnknownEvent,
    UnknownMessageSegment,
    UnknownNoticeEvent,
    Video,
    Xml,
    # <<< AUTO-GENERATED: TYPES IMPORTS END
)

__all__ = [
    "NapCatClient",
    "ReverseWebSocketServer",
    # >>> AUTO-GENERATED: TYPES EXPORTS START
    "NapCatEvent",
    "UnknownEvent",
    "MetaEvent",
    "LifecycleMetaEvent",
    "HeartbeatEvent",
    "HeartbeatStatus",
    "MessageEvent",
    "PrivateMessageEvent",
    "GroupMessageEvent",
    "MessageSender",
    "RequestEvent",
    "FriendRequestEvent",
    "GroupRequestEvent",
    "BotOfflineEvent",
    "FriendAddNoticeEvent",
    "FriendPokeEvent",
    "FriendRecallNoticeEvent",
    "GroupAdminNoticeEvent",
    "GroupBanEvent",
    "GroupCardEvent",
    "GroupDecreaseEvent",
    "GroupEssenceEvent",
    "GroupGrayTipEvent",
    "GroupIncreaseEvent",
    "GroupMsgEmojiLikeEvent",
    "GroupNameEvent",
    "GroupNoticeEvent",
    "GroupPokeEvent",
    "GroupRecallNoticeEvent",
    "GroupTitleEvent",
    "GroupUploadFile",
    "GroupUploadNoticeEvent",
    "InputStatusEvent",
    "MsgEmojiLike",
    "NoticeEvent",
    "OnlineFileNoticeEvent",
    "OnlineFileReceiveEvent",
    "OnlineFileSendEvent",
    "PokeEvent",
    "ProfileLikeEvent",
    "UnknownNoticeEvent",
    "MessageSegment",
    "UnknownMessageSegment",
    "At",
    "Contact",
    "CustomMusic",
    "Dice",
    "Face",
    "File",
    "FlashTransfer",
    "Forward",
    "IdMusic",
    "Image",
    "Json",
    "Location",
    "MFace",
    "Markdown",
    "Message",
    "MiniApp",
    "Node",
    "OnlineFile",
    "Poke",
    "RPS",
    "Record",
    "Reply",
    "Text",
    "Video",
    "Xml",
    # <<< AUTO-GENERATED: TYPES EXPORTS END
    "types",
]
