# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by NapCat Python SDK Generator

"""
BotOfflineEvent.py Event

OneBot 11 BotOfflineEvent.py 事件定义 (自动生成)。
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from .base import NoticeEvent


@dataclass(slots=True, frozen=True, kw_only=True)
class BotOfflineEvent(NoticeEvent):
    notice_type: Literal["bot_offline"] = "bot_offline"
    user_id: int
    tag: Literal["BotOfflineEvent"] | str = "BotOfflineEvent"
    message: Literal["BotOfflineEvent"] | str = "BotOfflineEvent"
