# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by NapCat Python SDK Generator

"""
FriendRecallNoticeEvent.py Event

OneBot 11 FriendRecallNoticeEvent.py 事件定义 (自动生成)。
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from .base import NoticeEvent


@dataclass(slots=True, frozen=True, kw_only=True)
class FriendRecallNoticeEvent(NoticeEvent):
    notice_type: Literal["friend_recall"] = "friend_recall"
    user_id: int
    message_id: int
