# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by NapCat Python SDK Generator

"""
FriendAddNoticeEvent.py Event

OneBot 11 FriendAddNoticeEvent.py 事件定义 (自动生成)。
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from .base import NoticeEvent


@dataclass(slots=True, frozen=True, kw_only=True)
class FriendAddNoticeEvent(NoticeEvent):
    notice_type: Literal["friend_add"] = "friend_add"
    user_id: int
