# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by NapCat Python SDK Generator

"""
GroupNameEvent.py Event

OneBot 11 GroupNameEvent.py 事件定义 (自动生成)。
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from .GroupNoticeEvent import GroupNoticeEvent


@dataclass(slots=True, frozen=True, kw_only=True)
class GroupNameEvent(GroupNoticeEvent):
    notice_type: Literal["notify"] = "notify"
    sub_type: Literal["group_name"] = "group_name"
    name_new: str
