# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by NapCat Python SDK Generator

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

from ...utils import FromDictMixin
from .GroupNoticeEvent import GroupNoticeEvent


@dataclass(slots=True, frozen=True, kw_only=True)
class GroupUploadFile(FromDictMixin):
    id: str
    name: str
    size: int
    busid: int


@dataclass(slots=True, frozen=True, kw_only=True)
class GroupUploadNoticeEvent(GroupNoticeEvent):
    notice_type: Literal["group_upload"] = "group_upload"
    file: GroupUploadFile

    @classmethod
    def _from_dict(cls, data: dict[str, Any]) -> GroupUploadNoticeEvent:
        if isinstance(data.get("file"), dict):
            data["file"] = GroupUploadFile._from_dict(data["file"])
        return super()._from_dict(data)
