# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by NapCat Python SDK Generator

"""
GroupIncreaseEvent.py Event

OneBot 11 GroupIncreaseEvent.py 事件定义 (自动生成)。
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from .GroupNoticeEvent import GroupNoticeEvent


@dataclass(slots=True, frozen=True, kw_only=True)
class GroupIncreaseEvent(GroupNoticeEvent):
    notice_type: Literal["group_increase"] = "group_increase"
    operator_id: int
    sub_type: Literal["approve", "invite"] = "approve"
