# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by NapCat Python SDK Generator

"""
GroupEssenceEvent.py Event

OneBot 11 GroupEssenceEvent.py 事件定义 (自动生成)。
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from .GroupNoticeEvent import GroupNoticeEvent


@dataclass(slots=True, frozen=True, kw_only=True)
class GroupEssenceEvent(GroupNoticeEvent):
    notice_type: Literal["essence"] = "essence"
    message_id: int
    sender_id: int
    operator_id: int
    sub_type: Literal["add", "delete"] = "add"
