# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by NapCat Python SDK Generator

"""
GroupBanEvent.py Event

OneBot 11 GroupBanEvent.py 事件定义 (自动生成)。
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from .GroupNoticeEvent import GroupNoticeEvent


@dataclass(slots=True, frozen=True, kw_only=True)
class GroupBanEvent(GroupNoticeEvent):
    notice_type: Literal["group_ban"] = "group_ban"
    operator_id: int
    duration: int
    sub_type: Literal["ban", "lift_ban"]
