# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by NapCat Python SDK Generator

"""
GroupCardEvent.py Event

OneBot 11 GroupCardEvent.py 事件定义 (自动生成)。
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from .GroupNoticeEvent import GroupNoticeEvent


@dataclass(slots=True, frozen=True, kw_only=True)
class GroupCardEvent(GroupNoticeEvent):
    notice_type: Literal["group_card"] = "group_card"
    card_new: str
    card_old: str
