# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by NapCat Python SDK Generator

"""
GroupNoticeEvent.py Event

OneBot 11 GroupNoticeEvent.py 事件定义 (自动生成)。
"""

from __future__ import annotations

from dataclasses import dataclass

from .base import NoticeEvent


@dataclass(slots=True, frozen=True, kw_only=True)
class GroupNoticeEvent(NoticeEvent):
    group_id: int
    user_id: int
