# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by NapCat Python SDK Generator

"""
GroupAdminNoticeEvent.py Event

OneBot 11 GroupAdminNoticeEvent.py 事件定义 (自动生成)。
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from .GroupNoticeEvent import GroupNoticeEvent


@dataclass(slots=True, frozen=True, kw_only=True)
class GroupAdminNoticeEvent(GroupNoticeEvent):
    notice_type: Literal["group_admin"] = "group_admin"
    sub_type: Literal["set", "unset"]
