# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by NapCat Python SDK Generator

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal, cast

from ...utils import FromDictMixin
from .GroupNoticeEvent import GroupNoticeEvent


@dataclass(slots=True, frozen=True, kw_only=True)
class MsgEmojiLike(FromDictMixin):
    emoji_id: str
    count: int


@dataclass(slots=True, frozen=True, kw_only=True)
class GroupMsgEmojiLikeEvent(GroupNoticeEvent):
    notice_type: Literal["group_msg_emoji_like"] = "group_msg_emoji_like"
    message_id: int
    likes: list[MsgEmojiLike]
    is_add: bool
    message_seq: str | None = None

    @classmethod
    def _from_dict(cls, data: dict[str, Any]) -> GroupMsgEmojiLikeEvent:
        payload: dict[str, Any] = dict(data)
        likes_raw = payload.get("likes")
        if isinstance(likes_raw, list):
            raw_items = cast(list[dict[str, Any]], likes_raw)
            payload["likes"] = [MsgEmojiLike._from_dict(item) for item in raw_items]
        return super()._from_dict(payload)
