# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by NapCat Python SDK Generator

"""
OnlineFileNoticeEvent.py Event

OneBot 11 OnlineFileNoticeEvent.py 事件定义 (自动生成)。
"""

from __future__ import annotations

from dataclasses import dataclass

from .base import NoticeEvent


@dataclass(slots=True, frozen=True, kw_only=True)
class OnlineFileNoticeEvent(NoticeEvent):
    peer_id: int
