# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by NapCat Python SDK Generator

"""
OnlineFileSendEvent.py Event

OneBot 11 OnlineFileSendEvent.py 事件定义 (自动生成)。
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from .OnlineFileNoticeEvent import OnlineFileNoticeEvent


@dataclass(slots=True, frozen=True, kw_only=True)
class OnlineFileSendEvent(OnlineFileNoticeEvent):
    notice_type: Literal["online_file_send"] = "online_file_send"
    sub_type: Literal["receive", "refuse"]
