# src/napcat/types/__init__.py
from .events import (
    GroupMessageEvent,
    HeartbeatEvent,
    LifecycleMetaEvent,
    MessageEvent,
    MessageSender,
    MetaEvent,
    NapCatEvent,
    PrivateMessageEvent,
    UnknownEvent,
    FriendRequestEvent,
    GroupRequestEvent,
    RequestEvent,
    HeartbeatStatus,
    # Notice Events
    BotOfflineEvent,
    FriendAddNoticeEvent,
    FriendPokeEvent,
    FriendRecallNoticeEvent,
    GroupAdminNoticeEvent,
    GroupBanEvent,
    GroupCardEvent,
    GroupDecreaseEvent,
    GroupEssenceEvent,
    GroupGrayTipEvent,
    GroupIncreaseEvent,
    GroupMsgEmojiLikeEvent,
    GroupNameEvent,
    GroupNoticeEvent,
    GroupPokeEvent,
    GroupRecallNoticeEvent,
    GroupTitleEvent,
    GroupUploadFile,
    GroupUploadNoticeEvent,
    InputStatusEvent,
    MsgEmojiLike,
    NoticeEvent,
    PokeEvent,
    ProfileLikeEvent,
    UnknownNoticeEvent,
)

from .messages import (
    At,
    Contact,
    CustomMusic,
    Dice,
    Face,
    File,
    FlashTransfer,
    Forward,
    IdMusic,
    Image,
    Json,
    Location,
    MFace,
    Markdown,
    Message,
    MiniApp,
    Node,
    OnlineFile,
    Poke,
    RPS,
    Record,
    Reply,
    Text,
    Video,
    Xml
)

from .messages import MessageSegment, UnknownMessageSegment

__all__ = [
    # events (most used)
    # Base
    "NapCatEvent",
    "UnknownEvent",
    # Meta Events
    "MetaEvent",
    "LifecycleMetaEvent",
    "HeartbeatEvent",
    "HeartbeatStatus",
    # Message Events
    "MessageEvent",
    "PrivateMessageEvent",
    "GroupMessageEvent",
    "MessageSender",
    # Request Events
    "RequestEvent",
    "FriendRequestEvent",
    "GroupRequestEvent",
    # Notice Events
    "BotOfflineEvent",
    "FriendAddNoticeEvent",
    "FriendPokeEvent",
    "FriendRecallNoticeEvent",
    "GroupAdminNoticeEvent",
    "GroupBanEvent",
    "GroupCardEvent",
    "GroupDecreaseEvent",
    "GroupEssenceEvent",
    "GroupGrayTipEvent",
    "GroupIncreaseEvent",
    "GroupMsgEmojiLikeEvent",
    "GroupNameEvent",
    "GroupNoticeEvent",
    "GroupPokeEvent",
    "GroupRecallNoticeEvent",
    "GroupTitleEvent",
    "GroupUploadFile",
    "GroupUploadNoticeEvent",
    "InputStatusEvent",
    "MsgEmojiLike",
    "NoticeEvent",
    "PokeEvent",
    "ProfileLikeEvent",
    "UnknownNoticeEvent",
    # message segments
    "MessageSegment",
    "UnknownMessageSegment",
    "At",
    "Contact",
    "CustomMusic",
    "Dice",
    "Face",
    "File",
    "FlashTransfer",
    "Forward",
    "IdMusic",
    "Image",
    "Json",
    "Location",
    "MFace",
    "Markdown",
    "Message",
    "MiniApp",
    "Node",
    "OnlineFile",
    "Poke",
    "RPS",
    "Record",
    "Reply",
    "Text",
    "Video",
    "Xml",
]
