# generated by datamodel-codegen:
#   filename:  schema.openapi.json
#   timestamp: 2026-01-14T08:52:40+00:00

from typing import Any, Literal, NotRequired, TypedDict


class Result(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: dict[str, Any]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class Group(TypedDict):
    group_all_shut: float
    group_remark: str
    group_id: str
    group_name: str
    member_count: float
    max_member_count: float


class GroupFile(TypedDict):
    file_size: float
    group_id: float
    file_id: str
    file_name: str
    busid: float
    size: float
    upload_time: float
    dead_time: float
    modify_time: float
    download_times: float
    uploader: float
    uploader_name: str


class GroupFileFolder(TypedDict):
    group_id: float
    folder_id: str
    folder: str
    folder_name: str
    create_time: float
    creator: float
    creator_name: str
    total_file_count: float


type UserSex = Literal["male", "female", "unknown"]


type GroupMemberRole = Literal["owner", "admin", "member"]


class 群荣誉信息(TypedDict):
    user_id: NotRequired[float]
    nickname: NotRequired[str]
    avatar: NotRequired[float]
    description: NotRequired[str]


type NumberString = float | str


class 点赞信息(TypedDict):
    uid: str
    src: float
    latestTime: float
    count: float
    giftCount: float
    customId: float
    lastCharged: float
    bAvailableCnt: float
    bTodayVotedCnt: float
    nick: str
    gender: float
    age: float
    isFriend: bool
    isvip: bool
    isSvip: bool
    uin: float


class 系统信息(TypedDict):
    request_id: float
    invitor_uin: float
    invitor_nick: str
    group_id: float
    message: str
    group_name: str
    checked: bool
    actor: float
    requester_nick: str


class MfaceData(TypedDict):
    emoji_package_id: float
    emoji_id: str
    key: str
    summary: str


class Mface(TypedDict):
    type: Literal["mface"]
    data: MfaceData


class TextData(TypedDict):
    text: str


class Text(TypedDict):
    type: Literal["text"]
    data: TextData


class PokeData(TypedDict):
    type: str
    id: str


class Poke(TypedDict):
    type: Literal["poke"]
    data: PokeData


class ContactData(TypedDict):
    type: str
    id: str


class Contact(TypedDict):
    type: Literal["contact"]
    data: ContactData


class FileBase(TypedDict):
    path: NotRequired[Literal["text"]]
    thumb: NotRequired[str]
    name: NotRequired[str]
    file: str
    url: NotRequired[str]


class ImageData(TypedDict):
    path: NotRequired[Literal["text"]]
    thumb: NotRequired[str]
    name: NotRequired[str]
    file: str
    url: NotRequired[str]
    summary: NotRequired[str]
    sub_type: NotRequired[Literal[0, 1, 2, 3, 4, 5, 6, 7]]


class Image(TypedDict):
    type: Literal["image"]
    data: ImageData


class Record(TypedDict):
    type: Literal["record"]
    data: FileBase


class File(TypedDict):
    type: Literal["file"]
    data: FileBase


class Video(TypedDict):
    type: Literal["video"]
    data: FileBase


class AtData(TypedDict):
    qq: Literal["qq", "group"]
    name: NotRequired[str]


class At(TypedDict):
    type: Literal["at"]
    data: AtData


class ReplyData(TypedDict):
    id: str


class Reply(TypedDict):
    type: Literal["reply"]
    data: ReplyData


class FaceData(TypedDict):
    id: str
    resultId: NotRequired[str]
    chainCount: NotRequired[float]


class Face(TypedDict):
    type: Literal["face"]
    data: FaceData


class NodeNew(TypedDict):
    text: str


class JsonDataConfig(TypedDict):
    token: str


class JsonData(TypedDict):
    data: str | dict[str, Any]
    config: NotRequired[JsonDataConfig]


class Json(TypedDict):
    type: Literal["json"]
    data: JsonData


class MarkdownData(TypedDict):
    content: str


class Markdown(TypedDict):
    type: Literal["markdown"]
    data: MarkdownData


class SendGroupMsgPostRequest(TypedDict):
    group_id: Any
    message: list[Any]


class SendGroupMsgPostResponseData(TypedDict):
    message_id: float


class SendGroupMsgPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: SendGroupMsgPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SendGroupForwardMsgPostResponseData(TypedDict):
    message_id: float
    res_id: str


class SendGroupForwardMsgPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: SendGroupForwardMsgPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class ForwardGroupSingleMsgPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GroupPokePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SendPrivateMsgPostRequest(TypedDict):
    user_id: Any
    message: list[Any]


class SendPrivateMsgPostResponseData(TypedDict):
    message_id: float


class SendPrivateMsgPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: SendPrivateMsgPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SendPrivateForwardMsgPostResponseData(TypedDict):
    message_id: float
    res_id: str


class SendPrivateForwardMsgPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: SendPrivateForwardMsgPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class ForwardFriendSingleMsgPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class FriendPokePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SendPokePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: NotRequired[None]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class DeleteMsgPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: NotRequired[None]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetForwardMsgPostResponseData(TypedDict):
    messages: list[Any]


class GetForwardMsgPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetForwardMsgPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetMsgEmojiLikePostResponseData(TypedDict):
    result: float
    errMsg: str


class SetMsgEmojiLikePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: SetMsgEmojiLikePostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class FetchEmojiLikePostResponseDataEmojiLikesListItem(TypedDict):
    tinyId: str
    nickName: str
    headUrl: str


class FetchEmojiLikePostResponseData(TypedDict):
    result: float
    errMsg: str
    emojiLikesList: list[FetchEmojiLikePostResponseDataEmojiLikesListItem]
    cookie: str
    isLastPage: bool
    isFirstPage: bool


class FetchEmojiLikePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: FetchEmojiLikePostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SendForwardMsgPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: dict[str, Any]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetRecordPostRequest(TypedDict):
    file: NotRequired[str]
    file_id: NotRequired[str]
    out_format: Literal["mp3", "amr", "wma", "m4a", "spx", "ogg", "wav", "flac"]


class GetRecordPostResponseData(TypedDict):
    file: str
    url: str
    file_size: str
    file_name: str
    base64: str


class GetRecordPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetRecordPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetImagePostRequest(TypedDict):
    file_id: NotRequired[str]
    file: NotRequired[str]


class GetImagePostResponseData(TypedDict):
    file: str
    url: str
    file_size: str
    file_name: str
    base64: str


class GetImagePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetImagePostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SendGroupAiRecordPostResponseData(TypedDict):
    message_id: str


class SendGroupAiRecordPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: SendGroupAiRecordPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetGroupAddOptionPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetGroupRobotAddOptionPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetGroupKickMembersPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetGroupRemarkPostRequest(TypedDict):
    group_id: str
    remark: str


class SetGroupRemarkPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetGroupSpecialTitlePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetGroupDetailInfoPostResponseData(TypedDict):
    group_all_shut: float
    group_remark: str
    group_id: float
    group_name: str
    member_count: float
    max_member_count: float


class GetGroupDetailInfoPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetGroupDetailInfoPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetGroupKickPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetGroupSystemMsgPostRequest(TypedDict):
    count: float


class SetGroupBanPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetEssenceMsgListPostResponseDatum(TypedDict):
    msg_seq: float
    msg_random: float
    sender_id: float
    sender_nick: str
    operator_id: float
    operator_nick: str
    message_id: float
    operator_time: float
    content: list[Any | dict[str, Any]]


class GetEssenceMsgListPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[GetEssenceMsgListPostResponseDatum]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetGroupWholeBanPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetGroupPortraitPostResponseData(TypedDict):
    result: str
    errMsg: str


class SetGroupPortraitPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: SetGroupPortraitPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetGroupAdminPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetGroupCardPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetEssenceMsgPostResponseDataResult(TypedDict):
    wording: str
    digestUin: str
    digestTime: float
    msg: dict[str, Any]
    errorCode: float


class SetEssenceMsgPostResponseData(TypedDict):
    errCode: str
    errMsg: str
    result: SetEssenceMsgPostResponseDataResult


class SetEssenceMsgPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: SetEssenceMsgPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetGroupNamePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class DeleteEssenceMsgPostResponseDataResult(TypedDict):
    wording: str
    digestUin: str
    digestTime: str
    msg: dict[str, Any]


class DeleteEssenceMsgPostResponseData(TypedDict):
    errCode: str
    errMsg: str
    result: DeleteEssenceMsgPostResponseDataResult


class DeleteEssenceMsgPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: DeleteEssenceMsgPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class FieldDelGroupNoticePostResponseData(TypedDict):
    result: float
    errMsg: str


class FieldDelGroupNoticePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: FieldDelGroupNoticePostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetGroupLeavePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class FieldSendGroupNoticePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetGroupSearchPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class FieldGetGroupNoticePostResponseDatumMessageItem(TypedDict):
    id: str
    height: str
    width: str


class FieldGetGroupNoticePostResponseDatum(TypedDict):
    notice_id: str
    sender_id: float
    publish_time: float
    message: list[FieldGetGroupNoticePostResponseDatumMessageItem]


class FieldGetGroupNoticePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[FieldGetGroupNoticePostResponseDatum]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetGroupAddRequestPostRequest(TypedDict):
    flag: str
    approve: bool
    reason: NotRequired[str]


class SetGroupAddRequestPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetGroupInfoPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: Group
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetGroupListPostRequest(TypedDict):
    no_cache: bool


class GetGroupListPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[Group]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetGroupInfoExPostResponseDataExtInfoGroupOwnerId(TypedDict):
    memberUin: str
    memberUid: str
    memberQid: str


class GetGroupInfoExPostResponseDataExtInfoGroupBindGuildIds(TypedDict):
    guildIds: list[str]


class GetGroupInfoExPostResponseDataExtInfoGroupExtFlameData(TypedDict):
    switchState: int
    state: int
    dayNums: list[str]
    version: int
    updateTime: str
    isDisplayDayNum: bool


class GetGroupInfoExPostResponseDataExtInfoGroupExcludeGuildIds(TypedDict):
    guildIds: list[str]


class GetGroupInfoExPostResponseDataExtInfo(TypedDict):
    groupInfoExtSeq: float
    reserve: float
    luckyWordId: str
    lightCharNum: float
    luckyWord: str
    starId: float
    essentialMsgSwitch: float
    todoSeq: float
    blacklistExpireTime: float
    isLimitGroupRtc: float
    companyId: float
    hasGroupCustomPortrait: float
    bindGuildId: str
    groupOwnerId: GetGroupInfoExPostResponseDataExtInfoGroupOwnerId
    essentialMsgPrivilege: float
    msgEventSeq: str
    inviteRobotSwitch: float
    gangUpId: str
    qqMusicMedalSwitch: float
    showPlayTogetherSwitch: float
    groupFlagPro1: str
    groupBindGuildIds: GetGroupInfoExPostResponseDataExtInfoGroupBindGuildIds
    viewedMsgDisappearTime: str
    groupExtFlameData: GetGroupInfoExPostResponseDataExtInfoGroupExtFlameData
    groupBindGuildSwitch: float
    groupAioBindGuildId: str
    groupExcludeGuildIds: GetGroupInfoExPostResponseDataExtInfoGroupExcludeGuildIds
    fullGroupExpansionSwitch: float
    fullGroupExpansionSeq: str
    inviteRobotMemberSwitch: float
    inviteRobotMemberExamine: float
    groupSquareSwitch: float


class GetGroupInfoExPostResponseData(TypedDict):
    groupCode: str
    resultCode: float
    extInfo: GetGroupInfoExPostResponseDataExtInfo


class GetGroupInfoExPostResponse(TypedDict):
    status: str
    retcode: float
    data: GetGroupInfoExPostResponseData
    message: str
    wording: str
    echo: None


class GetGroupAtAllRemainPostResponseData(TypedDict):
    can_at_all: bool
    remain_at_all_count_for_group: float
    remain_at_all_count_for_uin: float


class GetGroupAtAllRemainPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetGroupAtAllRemainPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetGroupShutListPostResponseDatum(TypedDict):
    uid: str
    qid: str
    uin: str
    nick: str
    remark: str
    cardType: float
    cardName: str
    role: float
    avatarPath: str
    shutUpTime: float
    isDelete: bool
    isSpecialConcerned: bool
    isSpecialShield: bool
    isRobot: bool
    groupHonor: dict[str, Any]
    memberRealLevel: float
    memberLevel: float
    globalGroupLevel: float
    globalGroupPoint: float
    memberTitleId: float
    memberSpecialTitle: str
    specialTitleExpireTime: str
    userShowFlag: float
    userShowFlagNew: float
    richFlag: float
    mssVipType: float
    bigClubLevel: float
    bigClubFlag: float
    autoRemark: str
    creditLevel: float
    joinTime: float
    lastSpeakTime: float
    memberFlag: float
    memberFlagExt: float
    memberMobileFlag: float
    memberFlagExt2: float
    isSpecialShielded: bool
    cardNameId: float


class GetGroupShutListPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[GetGroupShutListPostResponseDatum]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetGroupIgnoredNotifiesPostRequest(TypedDict):
    pass


class SetGroupSignPostRequest(TypedDict):
    group_id: str


class SetGroupSignPostResponse(TypedDict):
    pass


class SendGroupSignPostRequest(TypedDict):
    group_id: str


class SendGroupSignPostResponse(TypedDict):
    pass


class SetGroupTodoPostRequest(TypedDict):
    group_id: str
    message_id: str
    message_seq: NotRequired[str]


class SetGroupTodoPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: dict[str, Any]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetCookiesPostRequest(TypedDict):
    domain: str


class GetCookiesPostResponseData(TypedDict):
    cookies: str
    bkn: str


class GetCookiesPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetCookiesPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetCsrfTokenPostRequest(TypedDict):
    pass


class GetCsrfTokenPostResponseData(TypedDict):
    token: float


class GetCsrfTokenPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetCsrfTokenPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetCredentialsPostRequest(TypedDict):
    domain: str


class GetCredentialsPostResponseData(TypedDict):
    cookies: str
    token: float


class GetCredentialsPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetCredentialsPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class NcGetRkeyPostRequest(TypedDict):
    pass


class NcGetRkeyPostResponseDatum(TypedDict):
    rkey: str
    ttl: str
    time: float
    type: float


class NcGetRkeyPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[NcGetRkeyPostResponseDatum]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetRkeyPostRequest(TypedDict):
    pass


class GetRkeyPostResponseDatum(TypedDict):
    type: str
    rkey: str
    created_at: float
    ttl: str


class GetRkeyPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[GetRkeyPostResponseDatum]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetClientkeyPostRequest(TypedDict):
    pass


class GetClientkeyPostResponseData(TypedDict):
    clientkey: str


class GetClientkeyPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetClientkeyPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetRkeyServerPostRequest(TypedDict):
    pass


class GetRkeyServerPostResponseData(TypedDict):
    private_rkey: str
    group_rkey: str
    expired_time: float
    name: str


class GetRkeyServerPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetRkeyServerPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class CanSendImagePostRequest(TypedDict):
    pass


class CanSendImagePostResponseData(TypedDict):
    yes: bool


class CanSendImagePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: CanSendImagePostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class CanSendRecordPostRequest(TypedDict):
    pass


class CanSendRecordPostResponseData(TypedDict):
    yes: bool


class CanSendRecordPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: CanSendRecordPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class OcrImagePostRequest(TypedDict):
    image: str


class OcrImagePostResponseDatumPt1(TypedDict):
    x: str
    y: str


class OcrImagePostResponseDatumPt2(TypedDict):
    x: str
    y: str


class OcrImagePostResponseDatumPt3(TypedDict):
    x: str
    y: str


class OcrImagePostResponseDatumPt4(TypedDict):
    x: str
    y: str


class OcrImagePostResponseDatumCharBoxItemCharBoxPt1(TypedDict):
    x: str
    y: str


class OcrImagePostResponseDatumCharBoxItemCharBoxPt2(TypedDict):
    x: str
    y: str


class OcrImagePostResponseDatumCharBoxItemCharBoxPt3(TypedDict):
    x: str
    y: str


class OcrImagePostResponseDatumCharBoxItemCharBoxPt4(TypedDict):
    x: str
    y: str


class OcrImagePostResponseDatumCharBoxItemCharBox(TypedDict):
    pt1: OcrImagePostResponseDatumCharBoxItemCharBoxPt1
    pt2: OcrImagePostResponseDatumCharBoxItemCharBoxPt2
    pt3: OcrImagePostResponseDatumCharBoxItemCharBoxPt3
    pt4: OcrImagePostResponseDatumCharBoxItemCharBoxPt4


class OcrImagePostResponseDatumCharBoxItem(TypedDict):
    charText: str
    charBox: OcrImagePostResponseDatumCharBoxItemCharBox


class OcrImagePostResponseDatum(TypedDict):
    text: str
    pt1: OcrImagePostResponseDatumPt1
    pt2: OcrImagePostResponseDatumPt2
    pt3: OcrImagePostResponseDatumPt3
    pt4: OcrImagePostResponseDatumPt4
    charBox: list[OcrImagePostResponseDatumCharBoxItem]
    score: str


class OcrImagePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[OcrImagePostResponseDatum]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class FieldOcrImagePostRequest(TypedDict):
    image: str


class FieldOcrImagePostResponseDatumPt1(TypedDict):
    x: str
    y: str


class FieldOcrImagePostResponseDatumPt2(TypedDict):
    x: str
    y: str


class FieldOcrImagePostResponseDatumPt3(TypedDict):
    x: str
    y: str


class FieldOcrImagePostResponseDatumPt4(TypedDict):
    x: str
    y: str


class FieldOcrImagePostResponseDatumCharBoxItemCharBoxPt1(TypedDict):
    x: str
    y: str


class FieldOcrImagePostResponseDatumCharBoxItemCharBoxPt2(TypedDict):
    x: str
    y: str


class FieldOcrImagePostResponseDatumCharBoxItemCharBoxPt3(TypedDict):
    x: str
    y: str


class FieldOcrImagePostResponseDatumCharBoxItemCharBoxPt4(TypedDict):
    x: str
    y: str


class FieldOcrImagePostResponseDatumCharBoxItemCharBox(TypedDict):
    pt1: FieldOcrImagePostResponseDatumCharBoxItemCharBoxPt1
    pt2: FieldOcrImagePostResponseDatumCharBoxItemCharBoxPt2
    pt3: FieldOcrImagePostResponseDatumCharBoxItemCharBoxPt3
    pt4: FieldOcrImagePostResponseDatumCharBoxItemCharBoxPt4


class FieldOcrImagePostResponseDatumCharBoxItem(TypedDict):
    charText: str
    charBox: FieldOcrImagePostResponseDatumCharBoxItemCharBox


class FieldOcrImagePostResponseDatum(TypedDict):
    text: str
    pt1: FieldOcrImagePostResponseDatumPt1
    pt2: FieldOcrImagePostResponseDatumPt2
    pt3: FieldOcrImagePostResponseDatumPt3
    pt4: FieldOcrImagePostResponseDatumPt4
    charBox: list[FieldOcrImagePostResponseDatumCharBoxItem]
    score: str


class FieldOcrImagePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[FieldOcrImagePostResponseDatum]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class TranslateEn2zhPostRequest(TypedDict):
    words: list[str]


class TranslateEn2zhPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[str]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetInputStatusPostResponseData(TypedDict):
    result: float
    errMsg: str


class SetInputStatusPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: SetInputStatusPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class FieldHandleQuickOperationPostRequest(TypedDict):
    context: dict[str, Any]
    operation: dict[str, Any]


class FieldHandleQuickOperationPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetAiCharactersPostResponseDatumCharacter(TypedDict):
    character_id: str
    character_name: str
    preview_url: str


class GetAiCharactersPostResponseDatum(TypedDict):
    type: str
    characters: list[GetAiCharactersPostResponseDatumCharacter]


class GetAiCharactersPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[GetAiCharactersPostResponseDatum]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetAiRecordPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: str
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class ClickInlineKeyboardButtonPostResponseData(TypedDict):
    result: float
    errMsg: str
    status: float
    promptText: str
    promptType: float
    promptIcon: float


class ClickInlineKeyboardButtonPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: ClickInlineKeyboardButtonPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetVersionInfoPostRequest(TypedDict):
    pass


class GetVersionInfoPostResponseData(TypedDict):
    app_name: str
    protocol_version: str
    app_version: str


class GetVersionInfoPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetVersionInfoPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class NcGetPacketStatusPostRequest(TypedDict):
    pass


class NcGetPacketStatusPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: NotRequired[None]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SendPacketPostRequest(TypedDict):
    pass


class SendPacketPostResponse(TypedDict):
    pass


class GetRobotUinRangePostRequest(TypedDict):
    pass


class GetRobotUinRangePostResponseDatum(TypedDict):
    minUin: str
    maxUin: str


class GetRobotUinRangePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[GetRobotUinRangePostResponseDatum]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class BotExitPostRequest(TypedDict):
    pass


class BotExitPostResponse(TypedDict):
    pass


class CleanStreamTempFilePostRequest(TypedDict):
    pass


class CleanStreamTempFilePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: dict[str, Any]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class TestDownloadStreamPostRequest(TypedDict):
    error: NotRequired[bool]


class TestDownloadStreamPostResponseData(TypedDict):
    type: Literal["response"]
    data_type: Literal["data_complete"]
    data: Literal["Stream transmission complete"]


class TestDownloadStreamPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: TestDownloadStreamPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class UploadFileStreamPostRequest(TypedDict):
    stream_id: str
    chunk_data: NotRequired[str]
    chunk_index: NotRequired[float]
    total_chunks: NotRequired[float]
    file_size: NotRequired[float]
    expected_sha256: NotRequired[str]
    is_complete: NotRequired[bool]
    filename: NotRequired[str]
    reset: NotRequired[bool]
    verify_only: NotRequired[bool]
    file_retention: float


class UploadFileStreamPostResponseData(TypedDict):
    type: Literal["stream"]
    stream_id: str
    status: Literal["chunk_received", "file_created", "file_complete"]
    received_chunks: float
    total_chunks: float
    file_path: NotRequired[str]
    file_size: NotRequired[float]
    sha256: NotRequired[str]


class UploadFileStreamPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: UploadFileStreamPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class DownloadFileStreamPostRequest(TypedDict):
    file: NotRequired[str]
    file_id: NotRequired[str]
    chunk_size: NotRequired[float]


class DownloadFileStreamPostResponseData(TypedDict):
    type: Literal["response"]
    data_type: Literal["file_complete"]
    total_chunks: float
    total_bytes: float
    message: Literal["Download completed"]


class DownloadFileStreamPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: DownloadFileStreamPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class DownloadFileRecordStreamPostRequest(TypedDict):
    file: NotRequired[str]
    file_id: NotRequired[str]
    chunk_size: NotRequired[float]
    out_format: NotRequired[str]


class DownloadFileRecordStreamPostResponseData(TypedDict):
    type: Literal["response"]
    data_type: Literal["file_complete"]
    total_chunks: float
    total_bytes: float
    message: Literal["Download completed"]


class DownloadFileRecordStreamPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: DownloadFileRecordStreamPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class DownloadFileImageStreamPostRequest(TypedDict):
    file: NotRequired[str]
    file_id: NotRequired[str]
    chunk_size: NotRequired[float]


class DownloadFileImageStreamPostResponseData(TypedDict):
    type: Literal["response"]
    data_type: Literal["file_complete"]
    total_chunks: float
    total_bytes: float
    message: Literal["Download completed"]


class DownloadFileImageStreamPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: DownloadFileImageStreamPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class MarkMsgAsReadPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class MarkPrivateMsgAsReadPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class MarkGroupMsgAsReadPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetRecentContactPostRequest(TypedDict):
    count: NotRequired[float]


class FieldMarkAllAsReadPostRequest(TypedDict):
    pass


class FieldMarkAllAsReadPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SendLikePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetFriendAddRequestPostRequest(TypedDict):
    flag: str
    approve: bool
    remark: str


class SetFriendAddRequestPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetStrangerInfoPostResponseData(TypedDict):
    user_id: float
    uid: str
    uin: str
    nickname: str
    age: float
    qid: str
    qqLevel: float
    sex: str
    long_nick: str
    reg_time: float
    is_vip: bool
    is_years_vip: bool
    vip_level: float
    remark: str
    status: float
    login_days: float


class GetStrangerInfoPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetStrangerInfoPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetFriendListPostRequest(TypedDict):
    no_cache: bool


class GetFriendsWithCategoryPostRequest(TypedDict):
    pass


class SetQqProfilePostRequest(TypedDict):
    nickname: str
    personal_note: NotRequired[str]
    sex: NotRequired[UserSex]


class SetQqProfilePostResponseData(TypedDict):
    result: float
    errMsg: str


class SetQqProfilePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: SetQqProfilePostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class DeleteFriendPostResponseData(TypedDict):
    result: float
    errMsg: str


class DeleteFriendPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: DeleteFriendPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class ArkSharePeerPostResponseData(TypedDict):
    errCode: float
    errMsg: str
    arkJson: str


class ArkSharePeerPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: ArkSharePeerPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class ArkShareGroupPostRequest(TypedDict):
    group_id: str


class ArkShareGroupPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: str
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetOnlineStatusPostRequest(TypedDict):
    status: float
    extStatus: float
    batteryStatus: float


class SetOnlineStatusPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetDiyOnlineStatusPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: str
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetQqAvatarPostRequest(TypedDict):
    file: str


class SetQqAvatarPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class CreateCollectionPostRequest(TypedDict):
    rawData: str
    brief: str


class CreateCollectionPostResponseData(TypedDict):
    result: float
    errMsg: str


class CreateCollectionPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: CreateCollectionPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetSelfLongnickPostRequest(TypedDict):
    longNick: str


class SetSelfLongnickPostResponseData(TypedDict):
    result: float
    errMsg: str


class SetSelfLongnickPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: SetSelfLongnickPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class FetchCustomFacePostRequest(TypedDict):
    count: NotRequired[float]


class FetchCustomFacePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[str]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class NcGetUserStatusPostResponseData(TypedDict):
    status: float
    ext_status: float


class NcGetUserStatusPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: NcGetUserStatusPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetMiniAppArkPostRequestGetMiniAppArkPostRequest(TypedDict):
    type: Literal["bili", "weibo"]
    title: str
    desc: str
    picUrl: str
    jumpUrl: str
    webUrl: NotRequired[str]
    rawArkData: NotRequired[bool]


class GetMiniAppArkPostResponseDataMetaDataDetail1Host(TypedDict):
    uin: float
    nick: str


class GetMiniAppArkPostResponseDataMetaDataDetail1(TypedDict):
    appid: str
    appType: float
    title: str
    desc: str
    icon: str
    preview: str
    url: str
    scene: float
    host: GetMiniAppArkPostResponseDataMetaDataDetail1Host
    shareTemplateId: str
    shareTemplateData: dict[str, Any]
    showLittleTail: str
    gamePoints: str
    gamePointsUrl: str
    shareOrigin: float


class GetMiniAppArkPostResponseDataMetaData(TypedDict):
    detail_1: GetMiniAppArkPostResponseDataMetaDataDetail1


class GetMiniAppArkPostResponseDataConfig(TypedDict):
    type: str
    width: float
    height: float
    forward: float
    autoSize: float
    ctime: float
    token: str


class GetMiniAppArkPostResponseData(TypedDict):
    appName: str
    appView: str
    ver: str
    desc: str
    prompt: str
    metaData: GetMiniAppArkPostResponseDataMetaData
    config: GetMiniAppArkPostResponseDataConfig


class GetMiniAppArkPostResponseData1Config(TypedDict):
    type: str
    width: float
    height: float
    forward: float
    autoSize: float
    ctime: float
    token: str


class GetMiniAppArkPostResponseData1MetaDetail1Host(TypedDict):
    uin: float
    nick: str


class GetMiniAppArkPostResponseData1MetaDetail1(TypedDict):
    appid: str
    appType: float
    title: str
    desc: str
    icon: str
    preview: str
    url: str
    scene: float
    host: GetMiniAppArkPostResponseData1MetaDetail1Host
    shareTemplateId: str
    shareTemplateData: dict[str, Any]
    showLittleTail: str
    gamePoints: str
    gamePointsUrl: str
    shareOrigin: float


class GetMiniAppArkPostResponseData1Meta(TypedDict):
    detail_1: GetMiniAppArkPostResponseData1MetaDetail1


class GetMiniAppArkPostResponseData1(TypedDict):
    ver: str
    prompt: str
    config: GetMiniAppArkPostResponseData1Config
    app: str
    view: str
    meta: GetMiniAppArkPostResponseData1Meta
    miniappShareOrigin: float
    miniappOpenRefer: str


class GetMiniAppArkPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetMiniAppArkPostResponseData | GetMiniAppArkPostResponseData1
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetUnidirectionalFriendListPostRequest(TypedDict):
    pass


class GetUnidirectionalFriendListPostResponseDatum(TypedDict):
    uin: float
    uid: str
    nick_name: str
    age: float
    source: str


class GetUnidirectionalFriendListPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[GetUnidirectionalFriendListPostResponseDatum]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetLoginInfoPostRequest(TypedDict):
    pass


class GetLoginInfoPostResponseData(TypedDict):
    user_id: float
    nickname: str


class GetLoginInfoPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetLoginInfoPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetStatusPostRequest(TypedDict):
    pass


class GetStatusPostResponseData(TypedDict):
    online: bool
    good: bool
    stat: dict[str, Any]


class GetStatusPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetStatusPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetOnlineClientsPostRequest(TypedDict):
    pass


class GetOnlineClientsPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[str]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class FieldGetModelShowPostRequest(TypedDict):
    model: str


class FieldGetModelShowPostResponseDatumVariants(TypedDict):
    model_show: str
    need_pay: bool


class FieldGetModelShowPostResponseDatum(TypedDict):
    variants: FieldGetModelShowPostResponseDatumVariants


class FieldGetModelShowPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[FieldGetModelShowPostResponseDatum]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class FieldSetModelShowPostRequest(TypedDict):
    pass


class FieldSetModelShowPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetDoubtFriendsAddRequestPostRequest(TypedDict):
    count: float


class GetDoubtFriendsAddRequestPostResponseDatum(TypedDict):
    flag: str
    uin: str
    nick: str
    source: str
    reason: str
    msg: str
    group_code: str
    time: str
    type: str


class GetDoubtFriendsAddRequestPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[GetDoubtFriendsAddRequestPostResponseDatum]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetDoubtFriendsAddRequestPostRequest(TypedDict):
    flag: str
    approve: bool


class SetDoubtFriendsAddRequestPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: dict[str, Any]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetFriendRemarkPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class UploadGroupFilePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class UploadPrivateFilePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetGroupRootFilesPostResponseData(TypedDict):
    files: list[GroupFile]
    folders: list[GroupFileFolder]


class GetGroupRootFilesPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetGroupRootFilesPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetGroupFilesByFolderPostResponseData(TypedDict):
    files: list[GroupFile]
    folders: NotRequired[list[GroupFileFolder]]


class GetGroupFilesByFolderPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetGroupFilesByFolderPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetGroupFileSystemInfoPostResponseData(TypedDict):
    file_count: float
    limit_count: float
    used_space: float
    total_space: float


class GetGroupFileSystemInfoPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetGroupFileSystemInfoPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetFilePostRequest(TypedDict):
    file_id: NotRequired[str]
    file: NotRequired[str]


class GetFilePostResponseData(TypedDict):
    file: str
    url: str
    file_size: str
    file_name: str
    base64: str


class GetFilePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetFilePostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetGroupFileUrlPostResponseData(TypedDict):
    url: str


class GetGroupFileUrlPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetGroupFileUrlPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetPrivateFileUrlPostRequest(TypedDict):
    file_id: str


class GetPrivateFileUrlPostResponseData(TypedDict):
    url: str


class GetPrivateFileUrlPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetPrivateFileUrlPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class CreateGroupFileFolderPostResponseDataResult(TypedDict):
    retCode: float
    retMsg: str
    clientWording: str


class CreateGroupFileFolderPostResponseDataGroupItemFolderInfo(TypedDict):
    folderId: str
    parentFolderId: str
    folderName: str
    createTime: float
    modifyTime: float
    createUin: str
    creatorName: str
    totalFileCount: float
    modifyUin: str
    modifyName: str
    usedSpace: str


class CreateGroupFileFolderPostResponseDataGroupItem(TypedDict):
    peerId: str
    type: float
    folderInfo: CreateGroupFileFolderPostResponseDataGroupItemFolderInfo
    fileInfo: str | None


class CreateGroupFileFolderPostResponseData(TypedDict):
    result: CreateGroupFileFolderPostResponseDataResult
    groupItem: CreateGroupFileFolderPostResponseDataGroupItem


class CreateGroupFileFolderPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: CreateGroupFileFolderPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class DeleteGroupFilePostResponseDataTransGroupFileResultResult(TypedDict):
    retCode: float
    retMsg: str
    clientWording: str


class DeleteGroupFilePostResponseDataTransGroupFileResult(TypedDict):
    result: DeleteGroupFilePostResponseDataTransGroupFileResultResult
    successFileIdList: list[str]
    failFileIdList: list[str]


class DeleteGroupFilePostResponseData(TypedDict):
    result: float
    errMsg: str
    transGroupFileResult: DeleteGroupFilePostResponseDataTransGroupFileResult


class DeleteGroupFilePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: DeleteGroupFilePostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class DeleteGroupFolderPostResponseData(TypedDict):
    retCode: float
    retMsg: str
    clientWording: str


class DeleteGroupFolderPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: DeleteGroupFolderPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class MoveGroupFilePostResponseData(TypedDict):
    ok: bool


class MoveGroupFilePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: MoveGroupFilePostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class RenameGroupFilePostResponseData(TypedDict):
    ok: bool


class RenameGroupFilePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: RenameGroupFilePostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class TransGroupFilePostResponseData(TypedDict):
    ok: bool


class TransGroupFilePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: TransGroupFilePostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class DownloadFilePostRequest(TypedDict):
    url: NotRequired[str]
    base64: NotRequired[str]
    name: NotRequired[str]
    headers: NotRequired[str | list[str]]


class DownloadFilePostResponseData(TypedDict):
    file: str


class DownloadFilePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: DownloadFilePostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class CleanCachePostRequest(TypedDict):
    pass


class CleanCachePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: None
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class DelGroupAlbumMediaPostRequest(TypedDict):
    group_id: str
    album_id: str
    lloc: str


class SetGroupAlbumMediaLikePostRequest(TypedDict):
    group_id: str
    album_id: str
    lloc: str
    id: str
    set: bool


class DoGroupAlbumCommentPostRequest(TypedDict):
    group_id: str
    album_id: str
    lloc: str
    content: str


class DoGroupAlbumCommentPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: dict[str, Any]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetGroupAlbumMediaListPostRequest(TypedDict):
    group_id: str
    album_id: str
    attach_info: str


class UploadImageToQunAlbumPostRequest(TypedDict):
    group_id: str
    album_id: str
    album_name: str
    file: str


class UploadImageToQunAlbumPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: dict[str, Any]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetQunAlbumListPostRequest(TypedDict):
    group_id: str


class GetQunAlbumListPostResponseDatum(TypedDict):
    name: str
    album_id: str


class GetQunAlbumListPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[GetQunAlbumListPostResponseDatum]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SendMsgPostResponseData(TypedDict):
    message_id: float


class SendMsgPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: SendMsgPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class UnknownPostResponse(TypedDict):
    pass


class GetGuildListPostResponse(TypedDict):
    pass


class GetGuildServiceProfilePostResponse(TypedDict):
    pass


class CheckUrlSafelyPostResponse(TypedDict):
    pass


class GetCollectionListPostRequest(TypedDict):
    category: float
    count: float


class GetCollectionListPostResponseDataCollectionSearchListCollectionItemListItemAuthor(
    TypedDict
):
    type: float
    numId: str
    strId: str
    groupId: str
    groupName: str
    uid: str


class GetCollectionListPostResponseDataCollectionSearchListCollectionItemListItemSummary(
    TypedDict
):
    textSummary: str
    linkSummary: str
    gallerySummary: str
    audioSummary: str
    videoSummary: str
    fileSummary: str
    locationSummary: str
    richMediaSummary: str


class GetCollectionListPostResponseDataCollectionSearchListCollectionItemListItem(
    TypedDict
):
    cid: str
    type: float
    status: float
    author: GetCollectionListPostResponseDataCollectionSearchListCollectionItemListItemAuthor
    bid: float
    category: float
    createTime: str
    collectTime: str
    modifyTime: str
    sequence: str
    shareUrl: str
    customGroupId: float
    securityBeat: bool
    summary: GetCollectionListPostResponseDataCollectionSearchListCollectionItemListItemSummary


class GetCollectionListPostResponseDataCollectionSearchList(TypedDict):
    collectionItemList: list[
        GetCollectionListPostResponseDataCollectionSearchListCollectionItemListItem
    ]
    hasMore: bool
    bottomTimeStamp: str


class GetCollectionListPostResponseData(TypedDict):
    result: float
    errMsg: str
    collectionSearchList: GetCollectionListPostResponseDataCollectionSearchList


class GetCollectionListPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetCollectionListPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetGroupIgnoreAddRequestPostRequest(TypedDict):
    pass


class GetGroupIgnoreAddRequestPostResponseDatum(TypedDict):
    request_id: float
    invitor_uin: float
    invitor_nick: str | None
    group_id: float | None
    message: str | None
    group_name: str | None
    checked: bool
    actor: float
    requester_nick: str | None


class GetGroupIgnoreAddRequestPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[GetGroupIgnoreAddRequestPostResponseDatum]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class FieldE782B9E8B59EE4BFA1E681AF(TypedDict):
    uid: str
    src: float
    latestTime: float
    count: float
    giftCount: float
    customId: float
    lastCharged: float
    bAvailableCnt: float
    bTodayVotedCnt: float
    nick: str
    gender: float
    age: float
    isFriend: bool
    isvip: bool
    isSvip: bool
    uin: float


class FieldE7B3BBE7BB9FE4BFA1E681AF(TypedDict):
    request_id: float
    invitor_uin: float
    invitor_nick: str
    group_id: float
    message: str
    group_name: str
    checked: bool
    actor: float
    requester_nick: str


class FieldE7BEA4E88DA3E8AA89E4BFA1E681AF(TypedDict):
    user_id: NotRequired[float]
    nickname: NotRequired[str]
    avatar: NotRequired[float]
    description: NotRequired[str]


type Number207C20string = float | str


class Sender(TypedDict):
    user_id: float
    nickname: str
    sex: NotRequired[UserSex]
    age: NotRequired[float]
    card: NotRequired[str]
    level: NotRequired[str]
    role: NotRequired[GroupMemberRole]


class User(TypedDict):
    birthday_year: NotRequired[float]
    birthday_month: NotRequired[float]
    birthday_day: NotRequired[float]
    phone_num: NotRequired[str]
    email: NotRequired[str]
    category_id: NotRequired[float]
    user_id: float
    nickname: str
    remark: NotRequired[str]
    sex: NotRequired[UserSex]
    level: NotRequired[float]
    age: NotRequired[float]
    qid: NotRequired[str]
    login_days: NotRequired[float]
    categoryName: NotRequired[str]
    categoryId: NotRequired[float]


class GroupMember(TypedDict):
    group_id: float
    user_id: float
    nickname: str
    card: NotRequired[str]
    sex: NotRequired[UserSex]
    age: NotRequired[float]
    join_time: NotRequired[float]
    last_sent_time: NotRequired[float]
    level: NotRequired[float]
    qq_level: NotRequired[float]
    role: GroupMemberRole
    title: NotRequired[str]
    area: NotRequired[str]
    unfriendly: NotRequired[bool]
    title_expire_time: NotRequired[float]
    card_changeable: NotRequired[bool]
    shut_up_timestamp: NotRequired[float]
    is_robot: bool
    qage: NotRequired[str]


class 消息详情(TypedDict):
    self_id: float
    user_id: float
    time: float
    message_id: float
    message_seq: float
    real_id: float
    real_seq: str
    message_type: str
    sender: Sender
    raw_message: str
    font: float
    sub_type: str
    message: list[Any]
    message_format: str
    post_type: str
    group_id: NotRequired[float]


class MusicData(TypedDict):
    type: Literal["qq", "163", "kugou", "migu", "kuwo"]
    id: Number207C20string


class MusicData1(TypedDict):
    type: Literal["qq", "163", "kugou", "migu", "kuwo", "custom"]
    id: Number207C20string
    url: str
    audio: NotRequired[str]
    title: NotRequired[str]
    image: str
    content: NotRequired[str]


class Music(TypedDict):
    type: Literal["music"]
    data: MusicData | MusicData1


class DiceData(TypedDict):
    result: Number207C20string


class Dice(TypedDict):
    type: Literal["dice"]
    data: DiceData


class RpsData(TypedDict):
    result: Number207C20string


class Rps(TypedDict):
    type: Literal["rps"]
    data: RpsData


class ForwardGroupSingleMsgPostRequest(TypedDict):
    group_id: Number207C20string
    message_id: Number207C20string


class GroupPokePostRequest(TypedDict):
    group_id: Number207C20string
    user_id: Number207C20string


class ForwardFriendSingleMsgPostRequest(TypedDict):
    user_id: Number207C20string
    message_id: Number207C20string


class FriendPokePostRequest(TypedDict):
    user_id: Number207C20string
    target_id: NotRequired[Number207C20string]


class SendPokePostRequest(TypedDict):
    group_id: NotRequired[Number207C20string]
    user_id: Number207C20string
    target_id: NotRequired[Number207C20string]


class DeleteMsgPostRequest(TypedDict):
    message_id: Number207C20string


class GetGroupMsgHistoryPostRequest(TypedDict):
    group_id: Number207C20string
    message_seq: NotRequired[Number207C20string]
    count: NotRequired[float]
    reverseOrder: NotRequired[bool]


class GetMsgPostRequest(TypedDict):
    message_id: Number207C20string


class GetForwardMsgPostRequest(TypedDict):
    message_id: Number207C20string


class SetMsgEmojiLikePostRequest(TypedDict):
    message_id: Number207C20string
    emoji_id: float
    set: bool


class GetFriendMsgHistoryPostRequest(TypedDict):
    user_id: Number207C20string
    message_seq: NotRequired[Number207C20string]
    count: NotRequired[float]
    reverseOrder: NotRequired[bool]


class FetchEmojiLikePostRequest(TypedDict):
    message_id: Number207C20string
    emojiId: str
    emojiType: str
    count: NotRequired[float]


class SendGroupAiRecordPostRequest(TypedDict):
    group_id: Number207C20string
    character: str
    text: str


class SetGroupAddOptionPostRequest(TypedDict):
    group_id: Number207C20string
    add_type: str
    group_question: NotRequired[str]
    group_answer: NotRequired[str]


class SetGroupRobotAddOptionPostRequest(TypedDict):
    group_id: Number207C20string
    robot_member_switch: NotRequired[float]
    robot_member_examine: NotRequired[float]


class SetGroupKickMembersPostRequest(TypedDict):
    group_id: Number207C20string
    user_id: list[Number207C20string]
    reject_add_request: NotRequired[bool]


class SetGroupSpecialTitlePostRequest(TypedDict):
    group_id: Number207C20string
    user_id: Number207C20string
    special_title: NotRequired[str]


class GetGroupDetailInfoPostRequest(TypedDict):
    group_id: Number207C20string


class SetGroupKickPostRequest(TypedDict):
    group_id: Number207C20string
    user_id: Number207C20string
    reject_add_request: NotRequired[bool]


class GetGroupSystemMsgPostResponseData(TypedDict):
    InvitedRequest: list[FieldE7B3BBE7BB9FE4BFA1E681AF]
    join_requests: list[FieldE7B3BBE7BB9FE4BFA1E681AF]


class GetGroupSystemMsgPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetGroupSystemMsgPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetGroupBanPostRequest(TypedDict):
    group_id: Number207C20string
    user_id: Number207C20string
    duration: float


class GetEssenceMsgListPostRequest(TypedDict):
    group_id: Number207C20string


class SetGroupWholeBanPostRequest(TypedDict):
    group_id: Number207C20string
    enable: bool


class SetGroupPortraitPostRequest(TypedDict):
    group_id: Number207C20string
    file: str


class SetGroupAdminPostRequest(TypedDict):
    group_id: Number207C20string
    user_id: Number207C20string
    enable: bool


class SetGroupCardPostRequest(TypedDict):
    group_id: Number207C20string
    user_id: Number207C20string
    card: NotRequired[str]


class SetEssenceMsgPostRequest(TypedDict):
    message_id: Number207C20string


class SetGroupNamePostRequest(TypedDict):
    group_id: Number207C20string
    group_name: str


class DeleteEssenceMsgPostRequest(TypedDict):
    message_id: Number207C20string


class FieldDelGroupNoticePostRequest(TypedDict):
    group_id: Number207C20string
    notice_id: str


class SetGroupLeavePostRequest(TypedDict):
    group_id: Number207C20string
    is_dismiss: NotRequired[bool]


class FieldSendGroupNoticePostRequest(TypedDict):
    group_id: Number207C20string
    content: str
    image: NotRequired[str]
    pinned: NotRequired[Number207C20string]
    type: NotRequired[Number207C20string]
    confirm_required: NotRequired[Number207C20string]
    is_show_edit_card: NotRequired[Number207C20string]
    tip_window_type: NotRequired[Number207C20string]


class SetGroupSearchPostRequest(TypedDict):
    group_id: Number207C20string
    no_code_finger_open: NotRequired[float]
    no_finger_open: NotRequired[float]


class FieldGetGroupNoticePostRequest(TypedDict):
    group_id: Number207C20string


class GetGroupInfoPostRequest(TypedDict):
    group_id: Number207C20string


class GetGroupMemberInfoPostRequest(TypedDict):
    group_id: Number207C20string
    user_id: Number207C20string
    no_cache: bool


class GetGroupMemberInfoPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GroupMember
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetGroupMemberListPostRequest(TypedDict):
    group_id: Number207C20string
    no_cache: NotRequired[bool]


class GetGroupMemberListPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[GroupMember]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetGroupHonorInfoPostRequest(TypedDict):
    group_id: Number207C20string
    type: NotRequired[str]


class GetGroupHonorInfoPostResponseData(TypedDict):
    group_id: str
    current_talkative: FieldE7BEA4E88DA3E8AA89E4BFA1E681AF
    talkative_list: list[FieldE7BEA4E88DA3E8AA89E4BFA1E681AF]
    performer_list: list[FieldE7BEA4E88DA3E8AA89E4BFA1E681AF]
    legend_list: list[FieldE7BEA4E88DA3E8AA89E4BFA1E681AF]
    emotion_list: list[FieldE7BEA4E88DA3E8AA89E4BFA1E681AF]
    strong_newbie_list: list[FieldE7BEA4E88DA3E8AA89E4BFA1E681AF]


class GetGroupHonorInfoPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetGroupHonorInfoPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetGroupInfoExPostRequest(TypedDict):
    group_id: Number207C20string


class GetGroupAtAllRemainPostRequest(TypedDict):
    group_id: Number207C20string


class GetGroupShutListPostRequest(TypedDict):
    group_id: Number207C20string


class GetGroupIgnoredNotifiesPostResponseData(TypedDict):
    InvitedRequest: list[FieldE7B3BBE7BB9FE4BFA1E681AF]
    join_requests: list[FieldE7B3BBE7BB9FE4BFA1E681AF]


class GetGroupIgnoredNotifiesPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetGroupIgnoredNotifiesPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SetInputStatusPostRequest(TypedDict):
    user_id: Number207C20string
    event_type: float


class GetAiCharactersPostRequest(TypedDict):
    group_id: Number207C20string
    chat_type: NotRequired[float | str]


class GetAiRecordPostRequest(TypedDict):
    group_id: Number207C20string
    character: str
    text: str


class ClickInlineKeyboardButtonPostRequest(TypedDict):
    group_id: Number207C20string
    bot_appid: str
    button_id: str
    callback_data: str
    msg_seq: str


class MarkMsgAsReadPostRequest(TypedDict):
    group_id: NotRequired[Number207C20string]
    user_id: NotRequired[Number207C20string]


class MarkPrivateMsgAsReadPostRequest(TypedDict):
    user_id: Number207C20string


class MarkGroupMsgAsReadPostRequest(TypedDict):
    group_id: Number207C20string


class GetRecentContactPostResponseDatumLastestMsg(TypedDict):
    self_id: float
    user_id: float
    time: float
    real_seq: str
    message_type: str
    sender: Sender
    raw_message: str
    font: float
    sub_type: str
    message: list[Any]
    message_format: str
    post_type: str
    group_id: NotRequired[float]


class GetRecentContactPostResponseDatum(TypedDict):
    lastestMsg: NotRequired[GetRecentContactPostResponseDatumLastestMsg]
    peerUin: str
    remark: str
    msgTime: str
    chatType: float
    msgId: str
    sendNickName: str
    sendMemberName: str
    peerName: str


class GetRecentContactPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[GetRecentContactPostResponseDatum]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class SendLikePostRequest(TypedDict):
    user_id: Number207C20string
    times: NotRequired[float]


class GetStrangerInfoPostRequest(TypedDict):
    user_id: Number207C20string


class GetFriendListPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[User]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetFriendsWithCategoryPostResponseDatum(TypedDict):
    categoryId: float
    categorySortId: float
    categoryName: str
    categoryMbCount: float
    onlineCount: float
    buddyList: list[User]


class GetFriendsWithCategoryPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: list[GetFriendsWithCategoryPostResponseDatum]
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class DeleteFriendPostRequest(TypedDict):
    user_id: NotRequired[Number207C20string]
    friend_id: NotRequired[Number207C20string]
    temp_block: bool
    temp_both_del: bool


class ArkSharePeerPostRequest(TypedDict):
    group_id: NotRequired[Number207C20string]
    user_id: NotRequired[Number207C20string]
    phoneNumber: NotRequired[str]


class SetDiyOnlineStatusPostRequest(TypedDict):
    face_id: Number207C20string
    face_type: NotRequired[Number207C20string]
    wording: NotRequired[str]


class GetProfileLikePostRequest(TypedDict):
    user_id: NotRequired[Number207C20string]
    start: NotRequired[float]
    count: NotRequired[float]


class GetProfileLikePostResponseDataFavoriteInfo(TypedDict):
    total_count: float
    last_time: float
    today_count: float
    userInfos: list[FieldE782B9E8B59EE4BFA1E681AF]


class GetProfileLikePostResponseDataVoteInfo(TypedDict):
    total_count: float
    new_count: float
    new_nearby_count: float
    last_visit_time: float
    userInfos: list[FieldE782B9E8B59EE4BFA1E681AF]


class GetProfileLikePostResponseData(TypedDict):
    uid: str
    time: float
    favoriteInfo: GetProfileLikePostResponseDataFavoriteInfo
    voteInfo: GetProfileLikePostResponseDataVoteInfo


class GetProfileLikePostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetProfileLikePostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class NcGetUserStatusPostRequest(TypedDict):
    user_id: Number207C20string


class GetMiniAppArkPostRequestGetMiniAppArkPostRequest1(TypedDict):
    title: str
    desc: str
    picUrl: str
    jumpUrl: str
    iconUrl: str
    webUrl: NotRequired[str]
    appId: str
    scene: Number207C20string
    templateType: Number207C20string
    businessType: Number207C20string
    verType: Number207C20string
    shareType: Number207C20string
    versionId: str
    sdkId: str
    withShareTicket: Number207C20string
    rawArkData: NotRequired[bool]


type GetMiniAppArkPostRequest = (
    GetMiniAppArkPostRequestGetMiniAppArkPostRequest
    | GetMiniAppArkPostRequestGetMiniAppArkPostRequest1
)


class SetFriendRemarkPostRequest(TypedDict):
    user_id: Number207C20string
    remark: str


class UploadGroupFilePostRequest(TypedDict):
    group_id: Number207C20string
    file: str
    name: str
    folder: NotRequired[str]
    folder_id: NotRequired[str]


class UploadPrivateFilePostRequest(TypedDict):
    user_id: Number207C20string
    file: str
    name: str


class GetGroupRootFilesPostRequest(TypedDict):
    group_id: Number207C20string
    file_count: NotRequired[float]


class GetGroupFilesByFolderPostRequest(TypedDict):
    group_id: Number207C20string
    folder_id: NotRequired[str]
    folder: NotRequired[str]
    file_count: NotRequired[float]


class GetGroupFileSystemInfoPostRequest(TypedDict):
    group_id: Number207C20string


class GetGroupFileUrlPostRequest(TypedDict):
    group_id: Number207C20string
    file_id: str


class CreateGroupFileFolderPostRequest(TypedDict):
    group_id: Number207C20string
    folder_name: str


class DeleteGroupFilePostRequest(TypedDict):
    group_id: Number207C20string
    file_id: str


class DeleteGroupFolderPostRequest(TypedDict):
    group_id: Number207C20string
    folder_id: str


class MoveGroupFilePostRequest(TypedDict):
    group_id: Number207C20string
    file_id: str
    current_parent_directory: str
    target_parent_directory: str


class RenameGroupFilePostRequest(TypedDict):
    group_id: Number207C20string
    file_id: str
    current_parent_directory: str
    new_name: str


class TransGroupFilePostRequest(TypedDict):
    group_id: Number207C20string
    file_id: str


class FieldE6B688E681AFE8AFA6E68385(TypedDict):
    self_id: float
    user_id: float
    time: float
    message_id: float
    message_seq: float
    real_id: float
    real_seq: str
    message_type: str
    sender: Sender
    raw_message: str
    font: float
    sub_type: str
    message: list[Any]
    message_format: str
    post_type: str
    group_id: NotRequired[float]


class GetGroupMsgHistoryPostResponseData(TypedDict):
    messages: list[FieldE6B688E681AFE8AFA6E68385]


class GetGroupMsgHistoryPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetGroupMsgHistoryPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetMsgPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: FieldE6B688E681AFE8AFA6E68385
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class GetFriendMsgHistoryPostResponseData(TypedDict):
    messages: list[FieldE6B688E681AFE8AFA6E68385]


class GetFriendMsgHistoryPostResponse(TypedDict):
    status: Literal["ok"]
    retcode: float
    data: GetFriendMsgHistoryPostResponseData
    message: str
    echo: NotRequired[str | None]
    wording: NotRequired[str]
    stream: Literal["stream-action", "normal-action"]


class Message(TypedDict):
    real_seq: NotRequired[str]
    temp_source: NotRequired[float]
    message_sent_type: NotRequired[str]
    target_id: NotRequired[float]
    self_id: NotRequired[float]
    time: float
    message_id: float
    message_seq: float
    real_id: float
    user_id: Number207C20string
    group_id: NotRequired[Number207C20string]
    group_name: NotRequired[str]
    message_type: Literal["private", "group"]
    sub_type: NotRequired[Literal["friend", "group", "normal"]]
    sender: Sender
    message: MessageData5B5D | str
    message_format: Literal["array", "string"]
    raw_message: str
    font: str
    post_type: NotRequired[
        Literal["meta_event", "request", "notice", "message", "message_sent"]
    ]
    raw: NotRequired[str]


class NodeData(TypedDict):
    id: NotRequired[str]
    user_id: NotRequired[Number207C20string]
    uin: NotRequired[Number207C20string]
    nickname: str
    name: NotRequired[str]
    content: MessageMixType
    time: NotRequired[str]


class Node(TypedDict):
    type: Literal["node"]
    data: NodeData
    news: list[NodeNew]
    source: str
    summary: str
    prompt: str


class ForwardData(TypedDict):
    id: str
    content: NotRequired[Message]


class Forward(TypedDict):
    type: Literal["forward"]
    data: ForwardData


type MessageData = list[MessageDataModel]


type MessageDataModel = (
    Text
    | Face
    | Mface
    | At
    | Reply
    | Image
    | Record
    | File
    | Video
    | Node
    | Music
    | Json
    | Dice
    | Rps
    | Markdown
    | Forward
    | Contact
    | Poke
)


type MessageMixType = MessageData5B5D | MessageDataModel | str


class SendGroupForwardMsgPostRequest(TypedDict):
    group_id: Number207C20string
    messages: list[Forward | Node]


class SendPrivateForwardMsgPostRequest(TypedDict):
    user_id: Number207C20string
    messages: list[Forward | Node]


class SendForwardMsgPostRequest(TypedDict):
    group_id: NotRequired[Number207C20string]
    user_id: NotRequired[Number207C20string]
    messages: list[Forward | Node]


class SendMsgPostRequest(TypedDict):
    message_type: Literal["group", "private"]
    group_id: Number207C20string
    user_id: Number207C20string
    message: list[MessageMixType]


type MessageData5B5D = list[MessageDataModel]
