import inspect
import re
import sys
from pathlib import Path
from typing import Any

try:
    from napcat.types import schemas
except ImportError:
    print("❌ 无法导入 src.napcat.types.schemas")
    sys.exit(1)

schema_json = {}

try:
    import json
    with open("schema.openapi.json", "r", encoding="utf-8") as f:
        schema_json: dict[str, Any] = json.load(f)
        schema_json: dict[str, Any] = schema_json.get("paths", {})
except Exception as e:
    print(f"❌ 无法加载 schema.openapi.json: {e}")

def to_snake_case(name: str) -> str:
    # 第一步：把 "HTTPResponse" 变成 "HTTP_Response"
    # 逻辑：找到非首字母的字符，后面跟着"一个大写+小写序列"，在它们中间加下划线
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    
    # 第二步：把 "UserIdentifier" 变成 "User_Identifier"
    # 逻辑：找到"小写或数字"，后面跟着"一个大写"，在它们中间加下划线
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()

def generate_mixin():
    print("🔄 正在生成 Mixin 类 (src/napcat/client_gen.py) ...")
    
    methods_code: list[str] = []
    used_schema_types: set[str] = set()
    
    # 遍历 schemas
    class_names = [name for name, _ in inspect.getmembers(schemas, inspect.isclass)]
    
    for name in class_names:
        if not name.endswith("PostRequest"):
            continue
        
        used_schema_types.add(name)
        # 将 SendGroupMsgPostRequest -> send_group_msg
        base_name = name[:-11]
        if f"/{base_name}" in schema_json:
            method_name = base_name
        else:
            method_name = to_snake_case(base_name)
        
        # 寻找对应的 Response 类
        response_class_name = f"{base_name}PostResponse"
        if response_class_name not in class_names:
            return_type = "dict[str, Any]"
        else:
            return_type = response_class_name
            used_schema_types.add(response_class_name)

        # 查找注释
        method_json = schema_json.get(f"/{method_name}", {}).get("post", {})
        if method_json:
            description = method_json.get("summary", "")
            tag = method_json.get("tags", [""])[0]
            docstring = f'        """\n        {description}\n\n        标签: {tag}\n        """'
        else:
            docstring = '        """\n        未提供描述。\n        """'

        # 核心逻辑：生成实际的函数体
        # 注意：这里我们假设 params 就是 kwargs，直接传给 call_action
        code_block = f"""
    async def {method_name}(self, **kwargs: Unpack[{name}]) -> {return_type}:
{docstring}
        return await self._client.call_action("{method_name}", kwargs)
"""
        methods_code.append(code_block)

    # === 生成导入语句块 ===
    # 排序以保证生成的代码稳定
    sorted_types = sorted(list(used_schema_types))
    
    # 格式化导入字符串，看起来更整洁
    import_lines = ["from .types.schemas import ("]
    for type_name in sorted_types:
        import_lines.append(f"    {type_name},")
    import_lines.append(")")
    
    schema_imports_str = "\n".join(import_lines)

    # 生成文件内容
    content = f"""# generated by generate_client_gen.py
# 不要手动修改此文件，请运行生成脚本更新。

from collections.abc import Mapping
from typing import Any, Unpack, Protocol
{schema_imports_str}

# 定义一个 Protocol，避免循环导入 Client 类，同时保证类型提示
class CallActionProtocol(Protocol):
    async def call_action(self, action: str, params: Mapping[str, Any] | None = None) -> Any: ...

class NapCatAPI:
    \"\"\"
    NapCat API 命名空间。
    所有自动生成的方法都挂载于此，通过 client.api.xxx 调用。
    \"\"\"

    def __init__(self, client: CallActionProtocol):
        self._client = client

{ "".join(methods_code) }
"""

    output_path = Path("src/napcat/client_api.py")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"✅ 生成完成：{output_path} ({len(methods_code)} 个方法)")

if __name__ == "__main__":
    generate_mixin()