import libcst as cst

from .extractors import (
    collect_annotation_names_from_class,
    collect_annotation_names_from_module,
    collect_selected_type_alias_blocks,
    collect_top_level_definition_names,
    collect_typedict_helper_classes,
)
from .predicates import is_import_statement
from .transforms_typedict import DefinitionNameRemover


def build_generated_message_module(
    typedict_module: cst.Module,
    dataclass_module: cst.Module,
    typedict_definitions: dict[str, cst.ClassDef],
    generated_message_classes: list[cst.ClassDef],
) -> cst.Module:
    helper_typedict_classes = collect_typedict_helper_classes(
        generated_message_classes,
        typedict_module,
        typedict_definitions,
    )

    typing_import_names = ["Any", "Literal", "ClassVar"]
    if helper_typedict_classes:
        typing_import_names.append("TypedDict")

    has_not_required = any(
        "NotRequired" in collect_annotation_names_from_class(helper_cls)
        for helper_cls in helper_typedict_classes
    )
    if has_not_required:
        typing_import_names.append("NotRequired")

    generated_message_alias_blocks = collect_selected_type_alias_blocks(
        dataclass_module,
        {"OB11MessageData"},
    )

    generated_header = cst.parse_module(
        f"""
# generated by schema-codegen.py

from __future__ import annotations
from .base import MessageSegment
from dataclasses import dataclass
from typing import {", ".join(typing_import_names)}
"""
    )

    return cst.Module(
        body=[
            *generated_header.body,
            *helper_typedict_classes,
            *generated_message_classes,
            *generated_message_alias_blocks,
        ]
    )


def build_schemas_module(
    cleaned_typedict_module: cst.Module,
    generated_message_module: cst.Module,
    flattened_dataclass_names: set[str],
) -> tuple[cst.Module, list[str]]:
    generated_definition_names = sorted(
        collect_top_level_definition_names(generated_message_module)
    )
    generated_definition_name_set = set(generated_definition_names)

    referenced_names_in_schemas_source = collect_annotation_names_from_module(
        cleaned_typedict_module
    )
    schemas_names_to_remove = generated_definition_name_set | flattened_dataclass_names
    schemas_names_to_remove = {
        name
        for name in schemas_names_to_remove
        if name in generated_definition_name_set
        or name not in referenced_names_in_schemas_source
    }

    typedict_remover_for_schemas = DefinitionNameRemover(schemas_names_to_remove)
    schemas_typedict_module = cleaned_typedict_module.visit(typedict_remover_for_schemas)

    generated_import_module = cst.parse_module(
        "from .messages.generated import (\n"
        + "".join(f"    {name},\n" for name in generated_definition_names)
        + ")\n"
    )

    schemas_body = list(schemas_typedict_module.body)
    insert_index = 0
    for i, stmt in enumerate(schemas_body):
        if is_import_statement(stmt):
            insert_index = i + 1
            continue
        break

    schemas_module = cst.Module(
        body=[
            *schemas_body[:insert_index],
            *generated_import_module.body,
            *schemas_body[insert_index:],
        ]
    )

    return schemas_module, generated_definition_names
